import type { Lesson } from "./types";

const L = (
  order: number,
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ order, id, title, categoryId, tier: "tier1", intro, sections, checklist });

export const tier1Extra: Lesson[] = [
  L(36, "shimcache", "Shimcache — Execuções Antigas", "windows",
    "Shimcache (AppCompatCache) guarda histórico de execução mesmo quando Prefetch foi limpo.",
    [{ heading: "Onde", body: "Registry + parsers (AppCompatCacheParser). Mostra path e última execução.", example: "Shimcache: C:\\Temp\\loader_v3.exe — LastRun 14:29\nPrefetch: deletado\n→ Shimcache salva o dia." }],
    ["Exportar Shimcache", "Cruzar com BAM", "Timeline", "Print"]),
  L(37, "bam-detalhado", "BAM — Background Activity Moderator", "windows",
    "BAM registra executáveis por usuário — backup forense quando Prefetch sumiu.",
    [{ heading: "Registry path", body: "HKLM\\SYSTEM\\CurrentControlSet\\Services\\bam\\State\\UserSettings\\{SID}", example: "BAM entry: loader.exe — 09/06/2026 14:31:02 UTC" }],
    ["Achar SID do user", "Listar entradas BAM", "Cruzar prefetch", "Documentar"]),
  L(38, "startup-programs", "Programas de Inicialização", "windows",
    "Cheat que persiste no boot — Task Manager → Inicializar, registry Run, Startup folder.",
    [{ heading: "Locais", body: "shell:startup, HKCU Run, Task Scheduler on logon.", example: "Startup: 'WindowsHelper' → C:\\Users\\X\\AppData\\svc.exe" }],
    ["Task Manager Startup", "Run keys", "shell:startup", "Print"]),
  L(39, "bluestacks-paths", "Emulador — Paths BlueStacks", "deteccoes",
    "Saber onde o emulador instala ajuda a achar inject e configs de cheat.",
    [{ heading: "Paths", body: "ProgramData\\BlueStacks_nxt, HD-Player.exe, BstkSVC.log.", example: "Log BstkSVC com erro inject — linha suspeita 14:30" }],
    ["Identificar emu", "Processo principal", "Logs do emulador", "DLL list SI"]),
  L(40, "ldplayer-paths", "Emulador — LDPlayer / MEmu", "deteccoes",
    "Cada emulador tem processo e pasta diferente — não confundir na telagem.",
    [{ heading: "LDPlayer", body: "LdVBoxHeadless.exe, dnplayer.exe — pasta LDPlayer." }, { heading: "MEmu", body: "MEmuHeadless.exe, MemuSVC.exe." }],
    ["Qual emulador?", "Processo certo", "Inject target", "Print"]),
  L(41, "certutil-abuse", "Certutil — Download & Decode", "deteccoes",
    "Cheater usa certutil pra baixar/decode cheat sem browser.",
    [{ heading: "Comandos", body: "certutil -urlcache -split -f URL outfile | certutil -decode", example: "Prefetch CMD + certutil em journal\n→ Dropper via cmd" }],
    ["Prefetch cmd", "Journal certutil", "Arquivo gerado", "DIE"]),
  L(42, "bitsadmin-abuse", "Bitsadmin — Download Silencioso", "deteccoes",
    "BITS transfer baixa arquivo em background — menos visível que browser.",
    [{ heading: "Sinal", body: "bitsadmin /transfer job URL path — prefetch cmd ou powershell.", example: "bitsadmin transfer → C:\\Temp\\stage.exe" }],
    ["BITS logs", "Prefetch", "Arquivo destino", "SHA"]),
  L(43, "lnk-forense", "Análise de Atalhos (.lnk)", "windows",
    ".lnk guarda path alvo, argumentos e timestamp — prova abertura de arquivo.",
    [{ heading: "Ferramenta", body: "LECmd ou manual. Target path + args revelam cheat path.", example: ".lnk → C:\\Users\\X\\Downloads\\cheat_setup.exe\nAcessado: hoje 13:55" }],
    ["Export Recent .lnk", "Parse target", "Args suspeitos", "Print"]),
  L(44, "wer-basico", "WER — Relatórios de Erro", "windows",
    "Windows Error Reporting acumula relatórios — crash de inject aparece aqui.",
    [{ heading: "Path", body: "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportArchive", example: "Report: HD-Player.exe crash — faulting module inject.dll" }],
    ["WER folder", "Faulting module", "Data crash", "Cruzar Event 1000"]),
  L(45, "task-scheduler", "Agendador de Tarefas", "deteccoes",
    "Persistência via tarefa agendada — cheat roda no logon sem Startup visível.",
    [{ heading: "taskschd.msc", body: "Filtrar por autor do user. Ação apontando .exe em Temp/AppData.", example: "Task 'OneDriveSync' → C:\\Temp\\sync.exe (fake name)" }],
    ["Abrir Task Scheduler", "Tasks do user", "Ação/trigger", "Print"]),
  L(46, "reg-persistence", "Registry — Persistência Run/RunOnce", "deteccoes",
    "Run keys clássicas — cheat no boot.",
    [{ heading: "Keys", body: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run", example: "Valor: SecurityUpdate → loader.exe em AppData" }],
    ["regedit Run", "RunOnce", "Valor suspeito", "Arquivo existe?"]),
  L(47, "hosts-dns-local", "Hosts & DNS Local", "deteccoes",
    "Manipulação de hosts bloqueia update AV ou redireciona auth.",
    [{ heading: "hosts", body: "C:\\Windows\\System32\\drivers\\etc\\hosts — entradas não-Microsoft.", example: "127.0.0.1 update.microsoft.com" }],
    ["Ler hosts", "Data modificação", "ipconfig /flushdns", "Print"]),
  L(48, "srum-network", "SRUM — Uso de Rede Detalhado", "windows",
    "System Resource Usage Monitor — tráfego por app com timestamp preciso.",
    [{ heading: "Parse", body: "SRUM em registry — apps, bytes, intervalo de tempo.", example: "SRUM: unknown.exe 38MB entre 14:20-14:45" }],
    ["Parse SRUM", "App desconhecido", "Intervalo", "Cruzar uso de dados"]),
  L(49, "emulador-input-lag", "Input Lag & Comportamento", "deteccoes",
    "Comportamento no emulador sem arquivo — aim perfeito, flick suspeito.",
    [{ heading: "Contexto", body: "Não bana só por gameplay. Use com evidência técnica.", example: "Gameplay suspeito + Event 10 + auth\n→ Combo justifica investigação" }],
    ["Evidência técnica primeiro", "Gameplay como apoio", "Regra servidor", "Relatório"]),
  L(50, "relatorio-tier1", "Montar Relatório — Tier I", "analise",
    "Template de relatório para aluno básico entregar pro staff.",
    [{ heading: "Template", body: "PIN | Data | Resumo | Evidências (numeradas) | Veredito | Anexos SHA", example: "EVID #1: Prefetch loader 14:31\nEVID #2: Defender exclusão C:\\cheat\nVEREDITO: BAN" }],
    ["Usar template", "Numerar evidências", "SHA anexo", "Linguagem neutra"]),
];
