import type { Lesson } from "./types";

const L = (
  order: number,
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ order, id, title, categoryId, tier: "tier2", intro, sections, checklist });

export const tier2Extra: Lesson[] = [
  L(36, "sysmon-event-7", "Sysmon Event 7 — Image Loaded", "sysmon",
    "DLL carregada no processo = inject deixou digital. Event 7 mostra hook.dll no emulador unsigned. Xiter acha que sumiu.",
    [
      { kind: "intro", heading: "Image Loaded", body: "Event 7 registra toda DLL/.exe carregada em processo.\n\nCampos: ImageLoaded (path da DLL), Image (processo que carregou), Signed (status assinatura).\n\nInject clássico: HD-Player.exe loads C:\\Temp\\hook.dll — Unsigned." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Filtrar Event 7", body: "Sysmon Operational → Event ID 7.\n\nPeríodo: sessão de jogo.\n\nFiltra Image = HD-Player, LdVBoxHeadless, MEmu — processo do emulador.\n\nProcura: ImageLoaded em Temp, AppData, unsigned." },
      { kind: "tecnica", heading: "💉 DLL Unsigned no Emu", body: "HD-Player.exe loads C:\\Temp\\hook.dll — Signed: false\n\nPath Temp + unsigned + horário jogo = inject.\n\nCruza Event 8 CreateRemoteThread.", example: "Mano, HD-Player carregou hook.dll unsigned do Temp às 14:31. Tu tava jogando ou tu tava hookando?" },
      { kind: "tecnica", heading: "🔗 Event 7 + Event 11", body: "Event 11 drop inject.dll → Event 7 load no emulador.\n\nCadeia drop + load documentada.\n\nSHA ImageLoaded se arquivo existir." },
      { kind: "veredito", heading: "Event 7 na Telagem", body: "Unsigned em emulador = evidência forte.\n\nPrint Image + ImageLoaded + Signed.\n\nPath Temp = red flag." },
    ],
    ["Filtrar Event 7", "Unsigned em emulador", "Path Temp/AppData", "Cruzar Event 8", "Print"]),
  L(37, "sysmon-event-15", "Sysmon Event 15 — FileCreateStreamHash", "sysmon",
    "ADS — Alternate Data Streams. Cheat escondido em arquivo.txt:malware.bin. NTFS guarda. Xiter esquece que stream também loga.",
    [
      { kind: "intro", heading: "ADS no NTFS", body: "Alternate Data Stream — arquivo oculto anexado: notepad.exe:payload.bin\n\nEvent 15 FileCreateStreamHash — cria stream + hash.\n\nCheat escondido em :zone ou stream custom." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Event 15", body: "Filtra Event ID 15.\n\nProcura TargetFilename com : (dois pontos) — indica stream.\n\nExemplo: C:\\Temp\\doc.txt:hidden.exe" },
      { kind: "tecnica", heading: "📂 Stream Suspeito", body: "Event 15: notepad.exe:malware.bin criado por loader.exe\n\nStream em Temp/AppData.\n\ndir /r C:\\Temp — lista streams.", example: "Irmão, doc.txt:hidden.exe no Temp. Tu escondeu cheat em ADS ou tu escondeu IQ?" },
      { kind: "tecnica", heading: "🔍 dir /r", body: "Na SS: dir /r pasta suspeita.\n\nMostra streams NTFS.\n\nCruza Event 15 timestamp." },
      { kind: "veredito", heading: "ADS Documentado", body: "Event 15 stream + exec = suspeito forte.\n\nPrint dir /r + Event 15.\n\nDelete evidence — journal mostra." },
    ],
    ["Event 15", "Streams com :", "dir /r", "Journal delete", "Print"]),
  L(38, "sysmon-event-17", "Sysmon Event 17 — Pipe Created", "sysmon",
    "Named pipes — loader e cheat conversam por \\\\.\\pipe\\nome_aleatorio. Event 17 pega a ligação interna.",
    [
      { kind: "intro", heading: "Named Pipes", body: "IPC entre processos — loader ↔ cheat interno.\n\nEvent 17 Pipe Created.\n\nPipeName: \\\\.\\pipe\\msagent_28f2 — nomes random comuns." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Event 17", body: "Filtra Event ID 17.\n\nPeríodo: loader exec.\n\nProcura PipeName aleatório, Image = loader ou cheat." },
      { kind: "tecnica", heading: "🔌 Pipe Random", body: "Pipe: \\\\.\\pipe\\msagent_28f2\nImage: loader.exe\n\nComunicação interna cheat.\n\nCorrelaciona Event 1 loader + Event 17 pipe.", example: "Mano, loader criou pipe msagent_28f2. IPC de cheat interno. Explica?" },
      { kind: "tecnica", heading: "🔗 Process Creator", body: "Event 17 mostra quem criou pipe.\n\nCruza com processos ativos SI.\n\nPipe + Event 10 = combo interno." },
      { kind: "veredito", heading: "Pipe na Evidência", body: "Pipe random + loader = indicio forte.\n\nDocumenta PipeName + Image + horário." },
    ],
    ["Event 17", "Pipe name", "Process creator", "Correlacionar loader", "Print"]),
  L(39, "volatility-intro", "Volatility — Intro Memória", "avancado",
    "Dump .raw/.mem na mão? Volatility lista processo oculto, DLLs, strings. Tier II intro — o xiter escondeu do SI, não da RAM.",
    [
      { kind: "intro", heading: "Volatility intro", body: "Framework análise memória — dump RAM completo.\n\nPlugins: windows.pslist, dlllist, malfind, strings.\n\nProcesso oculto aparece. Tier II intro — Tier III aprofunda." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Quando Usar", body: "Dump .raw ou .mem do PC — ferramenta: DumpIt, WinPMEM, SI full dump.\n\nvol -f dump.raw windows.pslist\nvol -f dump.raw windows.dlllist\nvol -f dump.raw windows.malfind" },
      { kind: "tecnica", heading: "👻 Processo Oculto", body: "pslist mostra processo que SI não mostra — rootkit básico.\n\ndlllist — DLLs injetadas em processo.\n\nmalfind — regiões memória suspeitas.", example: "Dump raw: processo cheat_hidden.exe aparece. SI não mostrava. RAM não mente." },
      { kind: "tecnica", heading: "🔤 Strings na RAM", body: "vol windows.strings ou strings no dump.\n\nAuth, config, URLs.\n\nCorrelaciona com scan." },
      { kind: "veredito", heading: "Volatility Escalar", body: "Intro — usa pslist, dlllist.\n\nAchou oculto/inject = escalar Tier III.\n\nDocumenta comando + output." },
    ],
    ["Obter dump RAM", "pslist", "dlllist", "malfind/strings", "Documentar"]),
  L(40, "strings-advanced", "Strings — Caça Avançada", "avancado",
    "strings.exe, BinText, HxD — ASCII e Unicode. Auth, aimbot, inject failed. Binário fala se tu souber ouvir.",
    [
      { kind: "intro", heading: "Strings avançado", body: "Extrair strings legíveis de .exe, .dll, dump.\n\nASCII: strings.exe arquivo\nUnicode: strings -el arquivo\n\nAuth URLs, aimbot config, error messages." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Ferramentas", body: "strings.exe (Sysinternals)\nBinText\nHxD — manual\n\nBusca: licenseauth, keyauth, aimbot, inject, smooth, config, 0x5 access denied." },
      { kind: "tecnica", heading: "🔍 Loader Strings", body: "loader.exe strings:\nlicenseauth\ninject failed\n0x5 access denied\n\nConfissão no binário.", example: "Mano, loader.exe tem 'licenseauth' e 'inject failed 0x5'. Tu compilou isso ou tu comprou?" },
      { kind: "tecnica", heading: "🔤 Unicode Também", body: "Cheat ofusca ASCII — Unicode escondido.\n\nstrings -el dump.dmp\n\nURLs e keys em wide char." },
      { kind: "veredito", heading: "Strings Documentadas", body: "Excerpt no relatório — sem key real.\n\nCorrelaciona scan + dump.\n\nAuth URL = evidência." },
    ],
    ["strings no binário", "Unicode -el", "Auth URLs", "Dump strings", "Documentar excerpt"]),
  L(41, "vt-interpretacao", "VirusTotal — Interpretar Resultado", "avancado",
    "VT 0/72 NÃO é clean. VT 15/72 NÃO é ban automático. Cheat privado = zero detecções. Telador burro ban por VT e toma exposed.",
    [
      { kind: "intro", heading: "VT não é veredito", body: "VT 0/72 = cheat privado comum, packer, ou novo.\n\nVT 2/72 Heuristic = suspeito alto com contexto Temp.\n\nVT 15/72 genérico = investigar, não ban só VT." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Regra VT", body: "SHA no VT — lê detecções.\n\nHeuristic, packed, cheat gen = suspeito.\n\nContexto: path Temp, unsigned, exec Prefetch.\n\nNunca banir SÓ por VT." },
      { kind: "tecnica", heading: "📦 Packer + VT Baixo", body: "VT 2/72 Heuristic\nDIE: VMProtect\nPath: Temp\nPrefetch: exec 14:29\n\n= Suspeito alto mesmo VT baixo.", example: "VT 2/72 mas Temp, VMProtect, exec antes jogo. VT limpo não limpa tu." },
      { kind: "tecnica", heading: "🔐 Privado = 0 Detecções", body: "Cheat privado custom = 0/72.\n\nNão confundir com clean.\n\nCombo exec + auth + path." },
      { kind: "veredito", heading: "VT no Relatório", body: "Cita VT como contexto, não veredito.\n\nSHA + detecções + path + exec." },
    ],
    ["SHA no VT", "Ler detecções", "Contexto path/exec", "DIE packer", "Não banir só VT"]),
  L(42, "ppid-spoofing", "PPID Spoofing", "avancado",
    "Parent PID falso — loader parece filho de explorer. Sysmon Event 1 mente. System Informer mostra a verdade.",
    [
      { kind: "intro", heading: "PPID spoof", body: "Processo com parent PID falsificado.\n\nParentImage: explorer.exe mas explorer não spawnou.\n\nTécnica avançada — Sysmon Event 1 vs SI tree." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Detectar", body: "System Informer — process tree.\n\nParent não faz sentido — loader filho de explorer mas explorer sem handle.\n\nEvent 1 ParentImage vs SI parent real." },
      { kind: "tecnica", heading: "🌳 Mismatch Parent", body: "loader.exe ParentImage: explorer.exe\nSI: parent real = cmd.exe ou unknown\n\nTimestamps não batem.", example: "Mano, Sysmon diz explorer spawnou loader. SI diz cmd spawnou. Tu spoofou PPID ou tu spoofou telador?" },
      { kind: "tecnica", heading: "⏱️ Compare Timestamps", body: "Parent create time vs child create time.\n\nParent morreu antes child nascer = spoof.\n\nPrint SI tree + Event 1." },
      { kind: "veredito", heading: "PPID Documentado", body: "Spoof = técnica avançada = suspeito forte.\n\nEscalar se combo inject.\n\nPrint tree + Event 1." },
    ],
    ["SI process tree", "Event 1 Parent", "Compare timestamps", "Print mismatch", "Escalar"]),
  L(43, "lsass-access", "Acesso ao LSASS", "avancado",
    "Credential dump e alguns cheats acessam lsass. Event 10 target lsass.exe — Source suspeito = mimikatz pattern ou worse.",
    [
      { kind: "intro", heading: "LSASS access", body: "lsass.exe guarda credenciais.\n\nEvent 10 ProcessAccess — Target: lsass.exe\nSource suspeito + GrantedAccess alto = dump ou cheat avançado." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Event 10 lsass", body: "Filtra Event 10.\n\nTargetImage: lsass.exe\n\nSourceImage: não system, não antivírus.\n\nGrantedAccess: 0x1010, 0x1FFFFF suspeito." },
      { kind: "tecnica", heading: "🔓 Mimikatz Pattern", body: "Source: unknown.exe → lsass\nAccess: PROCESS_VM_READ | PROCESS_QUERY_INFORMATION\n\nMimikatz ou cheat que lê credenciais.", example: "Mano, teu loader acessou lsass com ALL_ACCESS. Tu tava logando ou dumpando?" },
      { kind: "veredito", heading: "LSASS Ban", body: "Source suspeito + lsass + access alto = BAN se confirmado.\n\nPrint Event 10 completo.\n\nEscalar staff." },
    ],
    ["Event 10 lsass", "Source image", "Access mask", "Print evento", "Ban se confirmado"]),
  L(44, "wmi-persistence", "WMI — Persistência", "avancado",
    "Cheat via WMI subscription — fileless persistence. Logon trigger → Execute loader. Telador que não olha WMI perde.",
    [
      { kind: "intro", heading: "WMI persistence", body: "WMI EventFilter + EventConsumer = exec em trigger.\n\nFileless — sem .exe no Run.\n\nLogon, idle, timer — dispara loader." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Detectar WMI", body: "PowerShell admin:\nGet-WmiObject -Namespace root\\subscription -Class __EventFilter\nGet-WmiObject -Namespace root\\subscription -Class CommandLineEventConsumer\n\nConsumer command apontando loader." },
      { kind: "tecnica", heading: "📜 Filter + Consumer", body: "EventFilter: SELECT * FROM __InstanceCreationEvent ... Win32_LogonSession\nConsumer: Execute loader.exe\n\nPersistência fileless.", example: "WMI trigger logon → Execute C:\\Temp\\loader. Tu persistiu cheat ou tu persistiu burrice?" },
      { kind: "tecnica", heading: "🗑️ Remover Evidência", body: "Documenta antes remover.\n\nPrint Filter + Consumer.\n\nJournal pode mostrar WMI create." },
      { kind: "veredito", heading: "WMI Escalar", body: "WMI persistence = avançado.\n\nEscalar Tier III.\n\nDocumenta subscription completa." },
    ],
    ["WMI subscription", "Consumer command", "Filter query", "Print antes remover", "Escalar"]),
  L(45, "bcdedit-boot", "BCDEdit & Boot Config", "avancado",
    "testsigning Yes, nointegritychecks Yes = kernel driver cheat facilitado. bcdedit /enum entrega o xiter boot.",
    [
      { kind: "intro", heading: "Boot config", body: "bcdedit controla boot Windows.\n\ntestsigning Yes = drivers test mode\nnointegritychecks Yes = bypass integrity\n\nKernel cheat clássico." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — bcdedit /enum", body: "Admin cmd: bcdedit /enum\n\nProcura:\ntestsigning Yes\nnointegritychecks Yes\n\nPrint output." },
      { kind: "tecnica", heading: "🚗 Driver Cheat Combo", body: "testsigning Yes + nointegritychecks Yes + driver unsigned SI\n\n= Kernel load facilitado.", example: "Mano, testsigning e nointegritychecks Yes. Tu boota Windows ou tu boota cheat kernel?" },
      { kind: "tecnica", heading: "🔐 Secure Boot", body: "Cruza msinfo32 Secure Boot off.\n\nCombo boot config + UEFI = escalar." },
      { kind: "veredito", heading: "bcdedit Documentado", body: "testsigning + driver unsigned = BAN kernel.\n\nPrint bcdedit + SI drivers." },
    ],
    ["bcdedit /enum", "testsigning", "nointegritychecks", "Secure Boot", "SI drivers"]),
  L(46, "event-6008-6006", "Events 6006/6008 — Shutdown", "avancado",
    "Reinício antes da SS — 6008 unexpected. User limpou RAM ou crashou driver. Gap antes scan = suspeito clássico.",
    [
      { kind: "intro", heading: "Shutdown events", body: "6006 = clean shutdown\n6008 = unexpected shutdown (crash, force)\n\nSystem log — reinício antes scan pedido." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — System Log", body: "Event Viewer → Windows Logs → System.\n\nFiltra 6006, 6008.\n\nHorário vs scan pedido.\n\n6008 14:25 — Scan 14:30 = reiniciou antes." },
      { kind: "tecnica", heading: "🔄 Gap Antes Scan", body: "Unexpected shutdown minutos antes SS.\n\nMotivo: limpar RAM, crash driver cheat, panic.\n\nPergunta direto.", example: "Mano, 6008 às 14:25, scan pedido 14:30. Tu reiniciou pra limpar RAM ou tu reiniciou teu argumento?" },
      { kind: "tecnica", heading: "⏱️ Timeline", body: "6008 + Prefetch vazio + serviços off = combo.\n\nDocumenta gap." },
      { kind: "veredito", heading: "Shutdown Suspeito", body: "6008 antes scan = suspeito.\n\nNão ban só — combo anti-forense.\n\nPerguntar motivo, documentar resposta." },
    ],
    ["System log 6006/6008", "Horário shutdown", "Gap antes scan", "Perguntar motivo", "Timeline"]),
  L(47, "event-104-log-clear", "Event 104 — Log Cleared (System)", "avancado",
    "1102 é Security. 104 é System/Application cleared. Cheater limpa os dois e acha que telador só olha Security.",
    [
      { kind: "intro", heading: "Event 104", body: "Microsoft-Windows-Eventlog — log cleared.\n\n104 = System ou Application log limpo.\n\n1102 = Security log limpo.\n\nCheater limpa todos — procura 104 E 1102." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Onde Procurar", body: "Application log — Event 104\nSystem log — Event 104\nSecurity log — Event 1102\n\nPeríodo: antes scan.\n\n104 System cleared 14:27 = anti-forense." },
      { kind: "tecnica", heading: "🧹 Log Cleared Combo", body: "104 Application + 104 System + 1102 Security\n\n= Limpeza completa.\n\nTimeline com Journal delete.", example: "Mano, 104 System cleared 14:27, 1102 Security 14:27. Tu limpou log ou tu limpou culpa?" },
      { kind: "veredito", heading: "104 Documentado", body: "104/1102 antes scan = suspeito forte.\n\nPrint eventos. Timeline.\n\nBan se combo exec + clear." },
    ],
    ["Application 104", "System 104", "1102 Security", "Timeline", "Print"]),
  L(48, "minifilter-drivers", "Minifilter & Drivers de File System", "avancado",
    "Driver kernel minifilter intercepta arquivo — cheat esconde .exe do scan. SI Drivers, unsigned, nome random.",
    [
      { kind: "intro", heading: "Minifilter", body: "File system minifilter driver — intercepta I/O.\n\nCheat kernel esconde arquivos, bloqueia read.\n\nSI System → Drivers — unsigned, x7filter.sys." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Driver List", body: "System Informer → System → Drivers.\n\nFiltra minifilter, file system.\n\nUnsigned + nome random + load time jogo." },
      { kind: "tecnica", heading: "🚗 x7filter.sys", body: "Driver: x7filter.sys — unsigned — loaded 13:00\n\nMinifilter intercepta.\n\nScan kernel flags 171 ScreenS.", example: "Mano, x7filter.sys unsigned minifilter 13:00. Tu filtra arquivo ou tu filtra telador?" },
      { kind: "tecnica", heading: "🔗 Load Time", body: "Load minutes before emulador.\n\nCruza bcdedit testsigning.\n\nEscalar Tier III." },
      { kind: "veredito", heading: "Minifilter BAN", body: "Unsigned minifilter = kernel cheat.\n\nPrint SI. BAN se confirmado." },
    ],
    ["Driver list SI", "Assinatura", "Load time", "Scan kernel", "Escalar"]),
  L(49, "network-capture", "Captura de Rede — Wireshark Intro", "avancado",
    "Telagem ao vivo — auth traffic em tempo real. Wireshark loopback + adapter. DNS query licenseauth durante SS = flagrante.",
    [
      { kind: "intro", heading: "Wireshark intro", body: "Captura pacotes durante SS ao vivo.\n\nLoopback + adapter físico.\n\nFiltro: dns.qry.name, ip.addr, http.host.\n\nAuth ativo = flagrante." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Captura SS", body: "Wireshark — capture during SS.\n\nAdapter: loopback + Ethernet/WiFi.\n\nFiltro: dns.qry.name contains license\n\nOu ip.addr == auth IP" },
      { kind: "tecnica", heading: "🌐 DNS Auth Ao Vivo", body: "DNS query licenseauth durante SS.\n\nProcesso correlaciona — Task Manager + SI.\n\nAuth ativo = BAN flagrante.", example: "Mano, DNS licenseauth durante SS ao vivo. Tu validava key na minha cara?" },
      { kind: "tecnica", heading: "🔗 Correlacionar Processo", body: "Wireshark + SI network tab.\n\nQual processo fez query.\n\nEvent 22 + Wireshark = prova dupla." },
      { kind: "veredito", heading: "Captura Documentada", body: "Print Wireshark com timestamp.\n\nAuth domain visível.\n\nEscalar se complexo tunnel." },
    ],
    ["Captura durante SS", "Filtro DNS", "Auth domain", "Correlacionar processo", "Print"]),
  L(50, "relatorio-tier2", "Relatório Avançado — Tier II", "analise",
    "Relatório nível staff — timeline + Sysmon + memória. Executive summary → evidências → veredito. Zero retrabalho.",
    [
      { kind: "intro", heading: "Relatório Tier II", body: "Nível staff — não é relatório de Tier I.\n\nTimeline unificada + Sysmon IDs citados + artefatos memória.\n\nExecutive summary → Timeline → Sysmon → Disco → Veredito → Recomendações." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Estrutura", body: "1. Executive summary — 3 linhas\n2. Timeline HH:MM — 8+ eventos\n3. Sysmon highlights — IDs 1,3,7,8,10,11,22\n4. Artefatos disco — Prefetch, Journal\n5. Memória — dump strings se houver\n6. Veredito — BAN/SUSPEITO/CLEAN\n7. Recomendações — rescan, escalar Tier III" },
      { kind: "tecnica", heading: "📊 Exemplo Timeline", body: "TIMELINE 14:25-14:35:\n14:25 CCleaner\n14:28 200 deletes\n14:30 E1 loader\n14:31 E8 inject\n14:35 scan\n\nVEREDITO BAN — 4 evidências independentes", example: "Relatório: 'Timeline 8 eventos, Sysmon chain 1→11→8, dump auth strings. BAN — 4 evidências.'" },
      { kind: "tecnica", heading: "📎 Anexos", body: "SHA256 todos binários.\nPrints datados numerados.\nSysmon IDs citados explicitamente.\n\nRecomendação rescan se SUSPEITO." },
      { kind: "veredito", heading: "Tier II Fechado", body: "Staff aceita sem retrabalho.\n\nTimeline visual + Sysmon + SHA.\n\nLinguagem neutra, fatos numerados." },
    ],
    ["Timeline visual", "Sysmon IDs citados", "SHA anexos", "4+ evidências", "Recomendação rescan"]),
];
