import type { Lesson } from "./types";

const L = (
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ id, title, categoryId, tier: "tier2", intro, sections, checklist });

export const tier2Lessons: Lesson[] = [
  L("sysmon-event-1", "Sysmon Event 1 — Process Create", "sysmon",
    "Todo processo que nasce no PC deixa certidão de nascimento. O xiter acha que abriu o loader 'invisível'. O Sysmon Event 1 ri dele.",
    [
      { kind: "intro", heading: "O que o Event 1 registra", body: "Cada execução de .exe gera Event ID 1 no log Microsoft-Windows-Sysmon/Operational.\n\nCampos que importam: Image (caminho do .exe), CommandLine (argumentos), ParentImage (quem spawnou), User, Hashes (SHA256).\n\nBase de toda timeline forense. Sem Event 1, tu tá telando no escuro." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Abrindo o Log", body: "Na SS manda abrir:\n\n1. Event Viewer → Applications and Services Logs → Microsoft → Windows → Sysmon → Operational\n2. Filtra por Event ID 1\n3. Ordena por horário do ban ou da sessão suspeita\n\nProcura: .exe em Temp/Downloads, ParentImage estranho, CommandLine com -silent, -inject, -load." },
      { kind: "tecnica", heading: "🕵️ ParentImage vs Parent Real", body: "Xiter usa PPID spoof — ParentImage mostra explorer.exe mas o processo não é filho legítimo.\n\nCruza Event 1 com System Informer: árvore de processos mostra parent real.\n\nParentImage = powershell.exe spawnando loader.exe às 14:29 = script de download antes do jogo.", example: "Mano, o Sysmon diz que o explorer.exe pariu teu loader às 14:29. Só que o explorer nem tava acordado nesse horário. Tu spawnou processo ou tu spawnou mentira?" },
      { kind: "tecnica", heading: "📋 CommandLine — A Confissão Escrita", body: "Loader com -silent, -inject, -key=, caminhos pra .dll em Temp.\n\nPowerShell/cmd como parent + CommandLine curta = execução rápida de cheat.\n\nAnota Image + CommandLine + ParentImage + horário. Print datado." },
      { kind: "veredito", heading: "Fechando no Event 1", body: "Event 1 sozinho raramente é ban — mas com Event 11 (drop) + Event 8 (inject) vira cadeia.\n\nLoader em Temp spawnado por ps/cmd minutos antes do emulador = suspeito forte.\n\nDocumenta cada campo. Staff ama print com horário visível." },
    ],
    ["Filtrar Event ID 1 no Sysmon", "Checar ParentImage vs SI", "CommandLine suspeita", "Cruzar horário com ban", "Print datado", "Montar timeline"]),
  L("sysmon-event-3", "Sysmon Event 3 — Network Connect", "sysmon",
    "O cheat precisa falar com o servidor de auth. Event 3 é a gravação da ligação. Xiter bloqueia firewall, não bloqueia o Sysmon.",
    [
      { kind: "intro", heading: "Conexões TCP/UDP", body: "Event 3 registra toda conexão de rede iniciada por um processo.\n\nCampos: Image (quem conectou), DestinationIp, DestinationPort, Protocol.\n\nAuth servers, phone-home, remote bypass — tudo passa aqui se o processo não usar tunnel avançado." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Filtrando Event 3", body: "Event Viewer → Sysmon Operational → filtra Event ID 3.\n\nPeríodo: horário do jogo + 30 min antes.\n\nProcura: loader.exe, processos desconhecidos, IPs estrangeiros, portas 1337/5555/8080, domínios de auth." },
      { kind: "tecnica", heading: "🌐 IP Estrangeiro + Loader", body: "loader.exe → 185.x.x.x:443 = auth server fora do BR.\n\nCruza com Event 22 (DNS) — mesmo domínio resolve pro IP.\n\nProcesso em Temp conectando em IP desconhecido = red flag absoluta.", example: "Irmão, teu loader.exe ligou pro IP 185.220.x.x na porta 443. Isso não é update do Windows não. Qual painel de auth tu tava validando?" },
      { kind: "tecnica", heading: "🔁 Localhost — Tunnel Burro", body: "127.0.0.1 e IP local podem ser tunnel de remote bypass ou IPC entre loader e cheat.\n\nloader.exe → 127.0.0.1:5555 = comunicação interna.\n\nTier III aprofunda remote deep — aqui anota e escala se combo suspeito." },
      { kind: "veredito", heading: "Network = Prova de Auth", body: "Event 3 + Event 22 + strings de auth no dump = combo matador.\n\nSó IP estranho sem execução = investigar, não ban direto.\n\nPrint Image + IP + Port + horário." },
    ],
    ["Filtrar Event 3", "IPs/portas estranhas", "Cruzar com Event 22", "Localhost suspeito", "Print datado"]),
  L("sysmon-event-11", "Sysmon Event 11 — FileCreate", "sysmon",
    "Loader dropa DLL no disco e acha que sumiu. Event 11 filmou cada byte escrito. Burro demais.",
    [
      { kind: "intro", heading: "Arquivo criado = rastro", body: "Event 11 registra criação de arquivo no disco.\n\nCampo chave: TargetFilename — caminho completo do arquivo criado.\n\nPadrão clássico: loader.exe cria inject.dll em Temp segundos antes do Event 8." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Caçando o Drop", body: "Filtra Event ID 11 no Sysmon Operational.\n\nPeríodo: minutos antes do inject (Event 8).\n\nProcura: TargetFilename em C:\\Temp, C:\\Users\\...\\AppData, extensão .dll/.exe, Image = loader ou cmd/ps." },
      { kind: "tecnica", heading: "💾 Drop + Inject Chain", body: "Sequência típica:\n14:30 Event 1 — loader.exe create\n14:30 Event 11 — C:\\Temp\\inject.dll create\n14:31 Event 8 — CreateRemoteThread no emulador\n\nTarget em Temp + unsigned + horário batendo = prova de drop.", example: "Mano, teu loader criou inject.dll no Temp às 14:30:02. Dois segundos depois tu injetou no HD-Player. Coincidência ou tu tava montando o kit de parede?" },
      { kind: "tecnica", heading: "🔐 SHA do Arquivo Dropado", body: "Event 11 às vezes traz hash. Se não, certutil -hashfile no arquivo se ainda existir.\n\nArquivo deletado? Journal mostra DELETE + Prefetch do loader.\n\nCruza SHA com VT e DIE." },
      { kind: "veredito", heading: "Event 11 na Cadeia", body: "Event 11 sozinho = suspeito. Event 11 + Event 8 = inject documentado.\n\nPrint TargetFilename + Image + horário. Anexa SHA se tiver." },
    ],
    ["Filtrar Event 11", "Target em Temp/AppData", "Cruzar Event 8", "SHA do drop", "Timeline drop→inject"]),
  L("sysmon-event-12", "Sysmon Event 12 — RegistryEvent", "sysmon",
    "Cheat que sobrevive reboot gruda no Registry. Event 12 pega a cola. Persistência burra = ban fácil.",
    [
      { kind: "intro", heading: "Registry = cola do cheat", body: "Event 12 registra create/set/delete de chaves e valores no Registry.\n\nCampos: ObjectName (caminho da chave), EventType (CreateKey, SetValue, DeleteKey).\n\nPersistência clássica: Run, RunOnce, serviços, IFEO." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Chaves Suspeitas", body: "Filtra Event ID 12. Procura ObjectName:\n\n• HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\n• HKLM\\...\\Run\n• HKLM\\SYSTEM\\CurrentControlSet\\Services\n• IFEO (Image File Execution Options)\n\nValor apontando .exe em Temp/Downloads = loader persistente." },
      { kind: "tecnica", heading: "🔑 Run Key — Clássico", body: "SetValue: HKCU\\Run\\Update → C:\\Temp\\loader.exe\n\nNome disfarçado (Update, WindowsService, OneDriveSync) + path suspeito.\n\nCruza com Event 1 no boot — loader executa sozinho.", example: "Ué, 'WindowsUpdateHelper' na chave Run apontando pro Temp? Desde quando update da Microsoft mora em C:\\Users\\User\\AppData\\Local\\Temp?" },
      { kind: "tecnica", heading: "⚙️ Serviço Criado via Registry", body: "Event 12 em HKLM\\...\\Services\\NomeRandom = driver ou serviço de cheat.\n\nCruza com services.msc e System Informer Drivers.\n\nPersistência + kernel = escalar Tier III." },
      { kind: "veredito", heading: "Registry na Telagem", body: "Event 12 com Run key + loader path = persistência documentada.\n\nPrint ObjectName + valor + horário. Cruza com scan 171 ScreenS." },
    ],
    ["Filtrar Event 12", "Run/RunOnce keys", "Serviços no Registry", "Print SetValue", "Cruzar boot Event 1"]),
  L("sysmon-event-22", "Sysmon Event 22 — DNSEvent", "sysmon",
    "Mesmo sem conexão TCP completa, a query DNS entrega o domínio de auth. O xiter esquece que DNS também loga.",
    [
      { kind: "intro", heading: "DNS revela auth", body: "Event 22 registra queries DNS feitas por processos.\n\nCampo chave: QueryName — domínio consultado.\n\nlicenseauth, keyauth, api.cheat-panel.com — listas públicas e privadas." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Filtrando DNS", body: "Event ID 22 no Sysmon Operational.\n\nPeríodo: sessão de jogo + 1h antes.\n\nProcura: QueryName com auth, license, key, api, cheat, panel, .cloud suspeito." },
      { kind: "tecnica", heading: "🔍 Domínios de Auth Conhecidos", body: "licenseauth.cloud, keyauth.win, fluxauth — padrões de mercado.\n\nQueryName + Image = loader.exe consultando api.licenseauth.cloud.\n\nCruza com Event 3 — mesmo IP na conexão.", example: "Mano, teu loader resolveu api.licenseauth.cloud às 14:28. Tu tava pesquisando receita de bolo ou validando key de aimbot?" },
      { kind: "tecnica", heading: "🕵️ Auth Privado — DNS Random", body: "Domínio que não está em listas públicas: api.x7k2-private.net.\n\nEvent 22 + Event 3 + dump strings = hunt de cheat privado.\n\nDocumenta QueryName + Image + horário." },
      { kind: "veredito", heading: "DNS na Evidência", body: "Event 22 sozinho = indicio forte de auth. Com Event 3 + execução = ban.\n\nPrint QueryName + Image. Timeline com Event 1 e 3." },
    ],
    ["Filtrar Event 22", "Domínios auth", "Cruzar Event 3", "Auth privado", "Timeline DNS"]),
  L("sysmon-hunting", "Sysmon Hunting — Regras e Config", "sysmon",
    "Telador que não sabe o que o Sysmon loga tá telando com olho fechado. Lê a config ou perde metade dos eventos.",
    [
      { kind: "intro", heading: "Sysmon sem config = buraco", body: "Sysmon instalado com config default ou SwiftonSecurity loga Event 1, 3, 7, 8, 10, 11, 12, 22 e mais.\n\nConfig em C:\\Windows\\sysmon.xml ou via Sysmon64 -c.\n\nSem Sysmon = zero Event 8/10/3. Cheater desinstala ou servidor não exige." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Verificar Instalação", body: "Na SS:\n\n1. services.msc → Sysmon64 existe? Running?\n2. Event Viewer → Sysmon Operational → tem logs recentes?\n3. Sysmon64 -c → mostra config ativa\n\nServidor exige Sysmon? Ausente = infração + suspeito." },
      { kind: "tecnica", heading: "📄 Ler sysmon.xml", body: "Regras definem o que loga e o que exclui.\n\nExclusão de Image = buraco intencional.\n\nSwiftonSecurity config = padrão ouro. Versão desatualizada = gaps.", example: "Irmão, teu servidor exige Sysmon e tu não tem serviço instalado. Tu desinstalou ou nunca instalou? Os dois cheiram a bypass." },
      { kind: "tecnica", heading: "🕳️ Gap de Logging", body: "Período sem eventos no Operational = log cleared, serviço parado, ou config que exclui tudo.\n\nCruza com Event 104/1102 (log cleared).\n\nGap antes do scan = anti-forense." },
      { kind: "veredito", heading: "Hunting Checklist", body: "Sysmon instalado + config ok + logs gerando = base Tier II.\n\nAusente/parado = suspeito + regra servidor.\n\nDocumenta versão e gap de logging." },
    ],
    ["Sysmon instalado?", "Config/versão", "Logs Operational", "Gap de logging", "Regra servidor"]),
  L("uefi-efi-basics", "UEFI / EFI — Fundamentos", "avancado",
    "Bootkit mora na partição EFI. Xiter acha que formatou o C: e limpou tudo. A ESP guarda o segredo.",
    [
      { kind: "intro", heading: "UEFI antes de bootkit", body: "Partição EFI System Partition (ESP) — FAT32 ~100MB.\n\nBootloaders .efi: bootmgfw.efi (Windows), grub, e arquivos desconhecidos.\n\nBootkit substitui ou adiciona .efi malicioso — persiste além do Windows." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Listar ESP", body: "mountvol (admin) ou diskpart:\n\n1. list vol → acha ESP (System, FAT32, ~100MB)\n2. assign letter=Z\n3. dir Z:\\EFI\\Microsoft\\Boot\\\n\nArquivos .efi desconhecidos, bootkit.efi, nomes random = escalar." },
      { kind: "tecnica", heading: "🔍 Arquivo Extra na ESP", body: "bootmgfw.efi legítimo + bootkit.efi ou hook.efi = bootkit.\n\nData de modificação recente + Secure Boot off = combo crítico.\n\nScan 171 ScreenS flags UEFI — correlaciona.", example: "Mano, bootkit.efi na partição EFI não veio de fábrica não. Tu instalou dual boot ou tu instalou dual cheat?" },
      { kind: "tecnica", heading: "📋 Secure Boot State", body: "msinfo32 → Secure Boot State: On/Off.\n\nOff sem dual boot legítimo = suspeito.\n\nCruza com scan UEFI flags." },
      { kind: "veredito", heading: "UEFI na Telagem", body: "Anomalia ESP + Secure Boot off = escalar Tier II/III.\n\nNão ban só por Secure Boot off — contexto (Linux dual boot) importa.\n\nPrint ESP listing + msinfo32." },
    ],
    ["Listar ESP", "Arquivos .efi", "Secure Boot state", "Scan UEFI flags", "Escalar se bootkit"]),
  L("uefi-secure-boot", "Secure Boot — Detecção", "avancado",
    "Secure Boot OFF não é ban automático. Mas competitive emu + OFF sem motivo = tu explica ou tu cai.",
    [
      { kind: "intro", heading: "Secure Boot = trava do boot", body: "Secure Boot impede bootloaders não assinados.\n\nOff = bootkit, dual boot Linux, ou driver cheat kernel (testsigning).\n\nContexto do user importa — competitive emu + off = perguntar." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — msinfo32", body: "Win+R → msinfo32 → System Summary.\n\nSecure Boot State: On ou Off.\n\nBIOS Mode: UEFI vs Legacy.\n\nPrint da tela. Pergunta: dual boot? Hackintosh? Modificou BIOS?" },
      { kind: "tecnica", heading: "⚠️ Off Sem Motivo Legítimo", body: "Competitive emu + Secure Boot OFF + scan UEFI anomaly = suspeito forte.\n\nDual boot documentado + Linux = pode ser legítimo.\n\nCruza com bcdedit (testsigning) e ESP check.", example: "Irmão, Secure Boot off, competitive emu, e scan acusou anomalia UEFI. Tu joga CS2 ou tu joga com bootkit?" },
      { kind: "zuera", heading: "🤣 Desculpa Clássica", body: "'Desliguei pra instalar driver de placa de vídeo' — 90% mentira.\n\n'Tenho Linux dual boot' — verifica ESP, pergunta qual distro.\n\n'Técnico fez' — técnico instalou cheat também." },
      { kind: "veredito", heading: "Secure Boot no Veredito", body: "Off sozinho = indicio. Off + UEFI flag + bcdedit testsigning = escalar.\n\nDocumenta msinfo32 + motivo declarado + ESP se possível." },
    ],
    ["msinfo32 Secure Boot", "BIOS mode UEFI", "Scan UEFI flags", "Motivo declarado", "Escalar se combo"]),
  L("servico-dns", "Serviço DNS — Tampering", "avancado",
    "Dnscache parado + hosts file + Event 22 estranho = alguém manipulou DNS pra auth ou redirect. Não é coincidência.",
    [
      { kind: "intro", heading: "DNS tampering", body: "Serviço Dnscache (DNS Client) cacheia queries.\n\nParado = poison ou bypass. hosts file redireciona domínios.\n\nCombo com Event 22 queries auth = interferência de rede." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Status Dnscache", body: "services.msc → DNS Client (Dnscache).\n\nStatus: Running ou Stopped?\nStartup: Automatic, Manual, Disabled?\n\nStopped + queries estranhas no Event 22 = tampering." },
      { kind: "tecnica", heading: "📄 hosts File", body: "C:\\Windows\\System32\\drivers\\etc\\hosts\n\nLinhas redirecionando auth domains pra 127.0.0.1 ou IP fake.\n\nCheat offline bypass ou redirect de license check.", example: "Mano, teu hosts file redireciona licenseauth.cloud pro localhost. Tu tava bloqueando ads ou bloqueando telador?" },
      { kind: "tecnica", heading: "🔍 ipconfig /displaydns", body: "Cache DNS ativo — domínios recentes.\n\nCruza com Event 22 QueryName.\n\nAuth domain no cache + loader no Prefetch = combo." },
      { kind: "veredito", heading: "DNS Tampering", body: "Dnscache stopped + hosts + Event 22 auth = suspeito forte.\n\nDocumenta status serviço + hosts content + Event 22." },
    ],
    ["Status Dnscache", "Event 22 queries", "hosts file", "ipconfig /displaydns", "Print"]),
  L("servico-sysmain", "SysMain (Superfetch) — Deep", "avancado",
    "SysMain OFF + Prefetch vazio num PC de 2 anos = anti-forense clássica. O xiter 'otimizou' e se entregou.",
    [
      { kind: "intro", heading: "SysMain = Prefetch", body: "SysMain (ex-Superfetch) gera arquivos Prefetch.\n\nDisabled = Prefetch não acumula ou fica vazio.\n\nCombo: SysMain off + 3 arquivos .pf + PC usado anos = tampering confirmado." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Verificar SysMain", body: "services.msc → SysMain (Superfetch).\n\nStatus e Startup type: Automatic, Manual, Disabled?\n\nCruza com contagem de .pf em C:\\Windows\\Prefetch." },
      { kind: "tecnica", heading: "📊 Prefetch Count vs Uso", body: "PC usado todo dia = dezenas de .pf em horas.\n\n3 arquivos .pf + SysMain Disabled + 2 anos de uso = script de cleaner ou bypass.", example: "Rapaz, SysMain desligado, Prefetch com 3 arquivos, PC de 2022. Tu usa Windows ou tu usa modo fantasma?" },
      { kind: "tecnica", heading: "🔗 Combo com Journal", body: "Journal mostra DELETE em massa em Prefetch?\n\nSysMain off + delete mass = dupla anti-forense.\n\nDocumenta startup type + prefetch count + journal." },
      { kind: "veredito", heading: "SysMain no Relatório", body: "SysMain off sozinho = suspeito. Com prefetch vazio + delete = anti-forense documentada.\n\nPrint services.msc + prefetch folder." },
    ],
    ["SysMain status", "Startup type", "Prefetch count", "Journal delete", "Relatório"]),
  L("servico-sysmon-svc", "Serviço Sysmon — Ausente/Parado", "avancado",
    "Servidor exige Sysmon. PC sem serviço = buraco na telagem + infração de regra. Cheater desinstala de propósito.",
    [
      { kind: "intro", heading: "Sem Sysmon = cego", body: "Event 8 (CreateRemoteThread), Event 10 (ProcessAccess), Event 3 (Network) — tudo depende do Sysmon.\n\nServiço Sysmon64 inexistente ou STOPPED = zero desses eventos.\n\nCheater desinstala ou nunca instalou." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Detectar Ausência", body: "services.msc → procura Sysmon64 ou Sysmon.\n\nExiste? Running? Startup type?\n\nEvent Viewer → Sysmon Operational → tem logs?\n\nRegra servidor: Sysmon obrigatório?" },
      { kind: "tecnica", heading: "🚫 Infração + Suspeito", body: "Regra: Sysmon obrigatório. PC: serviço ausente.\n\n= Infração de regra + suspeito de bypass.\n\nPergunta direto: desinstalou? Por quê?", example: "Mano, regra do servidor exige Sysmon. Teu PC não tem. Tu desinstalou pra esconder inject ou tu é sortudo demais?" },
      { kind: "tecnica", heading: "📋 Versão e Logs", body: "Se instalado: Sysmon64 -c mostra versão config.\n\nLogs gerando eventos recentes?\n\nGap de dias no Operational = parado ou cleared." },
      { kind: "veredito", heading: "Sysmon Ausente", body: "Ausente com regra = infração. Parado = suspeito.\n\nDocumenta regra servidor + status serviço + gap logs." },
    ],
    ["Serviço existe?", "Versão config", "Logs gerando?", "Regra servidor", "Gap logging"]),
  L("servico-diagtrack", "DiagTrack & DPS", "avancado",
    "DiagTrack, DPS, SysMain, EventLog off juntos = script de 'otimização' ou bypass tool. Pacote clássico.",
    [
      { kind: "intro", heading: "Telemetria off = padrão", body: "DiagTrack (Connected User Experiences), DPS (Diagnostic Policy Service) — telemetria Windows.\n\nDesligados junto com SysMain, EventLog, Defender = script de cleaner/bypass.\n\n4+ serviços forense/telemetry off = crítico." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Combo de Serviços", body: "services.msc — anota status:\n\n• DiagTrack\n• DPS\n• SysMain\n• EventLog (Windows Event Log)\n• Windows Defender\n• Dnscache\n\n3+ Disabled/Stopped = padrão bypass." },
      { kind: "tecnica", heading: "📜 Script de Otimização", body: "Prefetch de script .bat ou .ps1 que desliga serviços.\n\nJournal: CREATE otimizar.bat → EXEC → serviços off.\n\n171 ScreenS lista serviços off — usa como mapa.", example: "Irmão, 5 serviços de telemetria/forense off e Prefetch de 'Windows_Optimizer.bat'. Tu otimizou o PC ou otimizou a telagem?" },
      { kind: "veredito", heading: "Combo Serviços", body: "3+ off = suspeito forte. 5+ off + prefetch vazio = anti-forense.\n\nLista no relatório. Cruza com scan." },
    ],
    ["DiagTrack status", "DPS status", "Combo com SysMain", "Script em Prefetch?", "Relatório"]),
  L("journal-trace-avancado", "Journal Trace — Avançado", "avancado",
    "Rename chains, timestomp, selective delete — o xiter avançado tenta. O USN Journal é mais esperto que ele.",
    [
      { kind: "intro", heading: "Journal profundo", body: "USN Journal: CREATE, DELETE, RENAME, CLOSE.\n\nReason codes explicam a operação.\n\nCorrelacionar FILE_DELETE + FILE_CREATE no mesmo segundo = chain of obscurity." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Export e Filtro", body: "MFTECmd, JournalTrace ou área 171 ScreenS.\n\nExport completo do período do ban.\n\nFiltra por Reason codes, path Prefetch/Temp, horário." },
      { kind: "tecnica", heading: "🔄 Rename Chain", body: "RENAME cheat.exe → notepad.exe\nDELETE notepad.exe\nCREATE new_loader.exe\n\nXiter tenta confundir — timeline visual mata.", example: "Mano, renomeou cheat.exe pra notepad, deletou, criou new_loader. Tu tava organizando arquivos ou organizando mentira?" },
      { kind: "tecnica", heading: "⏱️ Timestomp + Selective Delete", body: "Timestomp altera MFT timestamps — journal pode mostrar inconsistência.\n\nSelective delete: só Prefetch/Temp/Logs, resto intacto.\n\nCorrelaciona com Prefetch e Sysmon gap." },
      { kind: "veredito", heading: "Journal Avançado", body: "Rename chain + delete mass + scan clean = anti-forense documentada.\n\nTimeline visual. Export PDF. Reason codes citados." },
    ],
    ["Export journal completo", "Reason codes", "Timeline visual", "Rename chains", "Correlacionar Prefetch"]),
  L("system-informer-avancado", "System Informer — Avançado", "avancado",
    "Handles em lsass, drivers kernel unsigned, PPID spoof, network oculta — System Informer é o raio-X do xiter vivo.",
    [
      { kind: "intro", heading: "SI além do básico", body: "System Informer (ex-Process Hacker) — processos, handles, drivers, memory, network.\n\nTelador Tier II usa: Handles tab, Drivers, PPID tree, hidden network." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Handles Suspeitos", body: "Processo cheat → Handles tab → procura handle em:\n\n• lsass.exe (credential dump)\n• csrss.exe\n• HD-Player.exe / emulador\n\nGranted access 0x1F0FFF = ALL_ACCESS suspeito." },
      { kind: "tecnica", heading: "🔌 Handle no Emulador", body: "cheat.exe handle → HD-Player PID\nGranted: 0x1F0FFF\n\nExternal read ou inject attempt.\n\nCruza com Event 10 ProcessAccess.", example: "Irmão, teu cheat.exe tem handle ALL_ACCESS no HD-Player. Tu tava admirando o processo ou lendo memória de aimbot?" },
      { kind: "tecnica", heading: "🚗 Drivers Kernel", body: "System → Drivers — lista drivers carregados.\n\nUnsigned + nome aleatório (x7k2.sys) = kernel cheat.\n\nLoad time vs horário do jogo." },
      { kind: "tecnica", heading: "🌳 PPID Spoof", body: "Process tree: parent não faz sentido.\n\nloader ParentImage explorer mas explorer não spawnou.\n\nCruza Event 1 ParentImage vs SI tree." },
      { kind: "veredito", heading: "SI na Telagem", body: "Handles + drivers + PPID = evidência ao vivo.\n\nPrint datado. Correlaciona Sysmon.\n\nNetwork hidden = escalar Tier III." },
    ],
    ["Handles tab emulador", "Drivers unsigned", "PPID tree", "Network hidden", "Print SI"]),
  L("dump-cheat", "Dump de Memória — Cheat", "avancado",
    "Arquivo apagado do disco? Processo ativo na SS? Strings na RAM não mentem. Dump mata o 'tô limpo'.",
    [
      { kind: "intro", heading: "Memória quando disco falha", body: "Dump de processo (.dmp) ou RAM completa (.raw).\n\nStrings: licenseauth, aimbot, inject failed, config keys.\n\nInternal sem arquivo, segunda opinião, scan suspeito disco limpo." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Quando Dumpar", body: "Cenários:\n\n• Processo cheat/emulador ativo durante SS\n• Internal sem .exe no disco\n• Scan acusa strings, disco limpo\n• Segunda opinião staff\n\nProcess Hacker/SI → Create dump file do processo." },
      { kind: "tecnica", heading: "🔤 strings.exe no Dump", body: "strings HD-Player.dmp | findstr /i auth aimbot inject license\n\nUnicode também: strings -el\n\nAuth URLs, config JSON, error messages de inject.", example: "Mano, teu HD-Player.dmp tem 'licenseauth.cloud' e 'aimbot smooth 0.8'. Disco limpo mas RAM suja. Explica?" },
      { kind: "tecnica", heading: "🔗 Correlacionar com Scan", body: "171 ScreenS strings + dump strings = mesma auth.\n\nEvent 8 + dump com inject.dll path = prova dupla.\n\nSHA do dump se staff pedir." },
      { kind: "veredito", heading: "Dump no Veredito", body: "Strings auth/aimbot em dump = evidência forte.\n\nDocumenta processo dumpado, ferramenta, strings encontradas.\n\nAnexa excerpt (sem key real)." },
    ],
    ["Dump processo correto", "strings.exe + Unicode", "Auth/aimbot strings", "Correlacionar scan", "Documentar"]),
  L("crashdumps", "Crashdumps (WER)", "avancado",
    "Windows Error Reporting guarda dumps de crash. Inject falhou? WER filmou. Xiter crashou e entregou prova.",
    [
      { kind: "intro", heading: "WER = cemitério de crash", body: "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportArchive\\\nC:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\\n\nLocalDumps registry — dumps automáticos por processo.\n\nCrash do emulador/cheat = strings no dump." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Onde Procurar", body: "1. WER ReportArchive — pastas por crash\n2. Registry: HKLM\\...\\Windows Error Reporting\\LocalDumps\n3. C:\\Users\\...\\AppData\\Local\\CrashDumps\n\nProcura HD-Player, emulador, inject.dll faulting." },
      { kind: "tecnica", heading: "💥 Inject Failed no Dump", body: "Crash dump HD-Player.exe\nStrings: inject failed 0x5, access denied, inject.dll\n\nTentativa de inject registrada no crash.", example: "Irmão, WER guardou dump do HD-Player com 'inject failed 0x5'. Tu crashou o emulador ou o cheat crashou teu argumento?" },
      { kind: "tecnica", heading: "🔗 Event 1000 + WER", body: "Event 1000 Application Error — Faulting module = inject.dll.\n\nWER dump mesmo processo, mesma DLL.\n\nProva dupla: log + dump." },
      { kind: "veredito", heading: "WER na Evidência", body: "Faulting inject.dll no 1000 + strings no WER dump = inject attempt documentado.\n\nData do crash vs horário ban." },
    ],
    ["WER folder", "LocalDumps registry", "Strings no dump", "Event 1000 faulting", "Data crash"]),
  L("event-1000-1001-1002", "Events 1000/1001/1002 — Application Error", "avancado",
    "Crashes e hangs do emulador/cheat — Application log guarda. Faulting module = inject.dll = confissão.",
    [
      { kind: "intro", heading: "Application Error events", body: "1000 = Application Error (crash)\n1001 = Windows Error Reporting (Watson)\n1002 = Application Hang\n\nFaulting application name, faulting module name, exception code." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Application Log", body: "Event Viewer → Windows Logs → Application.\n\nFiltra 1000, 1001, 1002.\n\nPeríodo: sessão de jogo. Procura HD-Player, emulador, inject.dll, cheat.exe." },
      { kind: "tecnica", heading: "💥 Faulting Module = inject.dll", body: "Event 1000:\nFaulting application: HD-Player.exe\nFaulting module: inject.dll\nException: 0xc0000005\n\nInject crashou — DLL no emulador falhou.", example: "Mano, Event 1000: HD-Player crashou por inject.dll. Tu tava jogando ou tu tava injetando?" },
      { kind: "tecnica", heading: "⏱️ Horário + Sysmon", body: "Crash 14:31 — Event 8 inject 14:30.\n\nTimeline: inject → crash.\n\nHang 1002 = cheat travou emulador." },
      { kind: "veredito", heading: "1000 na Cadeia", body: "1000 faulting inject.dll + Event 8 = inject documentado.\n\nPrint evento completo. Cruza WER dump." },
    ],
    ["Application log 1000/1001/1002", "Faulting module", "Horário vs Sysmon", "Cruzar WER", "Print"]),
  L("event-powershell-4104", "PowerShell Event 4104 — Script Block", "avancado",
    "Fileless cheat roda em PowerShell. Script Block Logging captura -enc, IEX, DownloadString. Xiter esquece que PS loga.",
    [
      { kind: "intro", heading: "4104 = script block", body: "PowerShell Operational log — Event 4104 Script Block Logging.\n\nCaptura conteúdo de scripts executados: -enc base64, IEX, DownloadString, Invoke-Expression.\n\nFileless loader clássico." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Habilitar e Filtrar", body: "4104 precisa estar habilitado (GPO ou registro).\n\nEvent Viewer → Applications and Services Logs → Microsoft → Windows → PowerShell → Operational\n\nFiltra 4104. Período do ban. Procura -enc, IEX, DownloadString, http." },
      { kind: "tecnica", heading: "🔓 Decode Base64", body: "4104: powershell -enc SQBFAFgAIAAo...\n\nDecode: [System.Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('...'))\n\nRevela DownloadString, URL, payload.", example: "Irmão, 4104 mostra IEX DownloadString de http://pastebin.../loader. Tu tava rodando script de 'otimização' ou loader fileless?" },
      { kind: "tecnica", heading: "🔗 Parent + Prefetch", body: "Event 1: powershell.exe parent cmd.exe\n4104: payload\nPrefetch: POWERSHELL.EXE minutos antes do jogo.\n\nCadeia fileless documentada." },
      { kind: "veredito", heading: "4104 no Veredito", body: "4104 com download cradle + exec = fileless loader.\n\nDecode e documenta URL. Escalar Tier III se complexo.\n\nPrint 4104 + parent process." },
    ],
    ["4104 habilitado?", "Filtrar período", "Decode base64", "Parent process", "Prefetch ps/cmd"]),
  L("hidden-bypass", "Hidden Bypass — Strings Ocultas", "bypass",
    "XOR, base64, auth ofuscada — scanner acha como Hidden Bypass. Xiter acha que ofuscou. Scanner não é burro.",
    [
      { kind: "intro", heading: "Hidden no 171 ScreenS", body: "Categoria Hidden Bypass — strings ofuscadas, XOR stubs, auth em base64.\n\nFarmservices, solvynx, packed loaders.\n\nPrivado ou genérico avançado." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Padrões", body: "Scan acusa Hidden Bypass.\n\nPrefetch: loader XOR packed.\n\nDIE: alta entropy, VMProtect/Themida.\n\nStrings memória: decode manual ou dump." },
      { kind: "tecnica", heading: "🔐 XOR e Base64", body: "Loader com strings XOR — scan detecta padrão.\n\nDump ou strings.exe no binário — auth aparece decode.\n\nContexto: Temp path + unsigned + Hidden = suspeito alto.", example: "Mano, scan Hidden Bypass solvynx, loader em Temp, entropy 7.8. Tu comprou curso de ofuscação ou curso de ban?" },
      { kind: "tecnica", heading: "🕵️ DIE + Entropy", body: "Detect It Easy — packer, protector, compiler.\n\nEntropy alta + Hidden flag = packed cheat.\n\nVT 0/72 não limpa — privado não detecta." },
      { kind: "veredito", heading: "Hidden Bypass", body: "Hidden + exec + Temp = suspeito forte.\n\nDocumenta scan flag + DIE + path.\n\nStrings memória se possível." },
    ],
    ["Hidden no scan", "Strings memória", "DIE entropy", "Contexto path", "Documentar"]),
  L("cheat-generico", "Cheat Genérico — Padrões de Mercado", "bypass",
    "KeyAuth, loaders, internal vs external — reconhecer rápido separa telador pro de amador que perde 40 min.",
    [
      { kind: "intro", heading: "Mercado de cheat", body: "Auth: KeyAuth, FluxAuth, LicenseAuth — URLs, AppData configs, Event 3 auth IP.\n\nExternal: loader → Event 10 → overlay, leitura memória.\n\nInternal: Event 8 + DLL unsigned no emulador." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Classificar Tipo", body: "External: processo separado, Event 10 ProcessAccess, overlay topmost, sem DLL no emu às vezes.\n\nInternal: Event 8 CreateRemoteThread, DLL no emulador, inject direto.\n\nLoader: Event 1 + 11 + auth Event 3/22." },
      { kind: "tecnica", heading: "🔑 Auth Evidence", body: "Event 3 IP auth, Event 22 DNS, AppData config .json, strings licenseauth.\n\nPadrão external: loader → Event 10 → emulador, overlay em SI.", example: "Irmão, loader KeyAuth no Prefetch, Event 3 pro IP de auth, overlay topmost. External clássico. Next?" },
      { kind: "tecnica", heading: "💉 Internal Pattern", body: "Event 8 + DLL unsigned em HD-Player.\n\nEvent 11 drop inject.dll.\n\nSem processo overlay — tudo dentro do emu." },
      { kind: "veredito", heading: "Classificação no Relatório", body: "Tipo: external/internal/loader.\n\nAuth evidence listada.\n\nInject vs read documentado." },
    ],
    ["Classificar tipo", "Auth evidence", "Inject vs read", "Overlay SI", "Relatório"]),
  L("det-inject-chain", "Detecção Avançada: Cadeia de Injeção", "deteccoes",
    "Event 1 → 11 → 8 → 5 em sequência = inject completo documentado. Timeline que staff aceita sem retrabalho.",
    [
      { kind: "intro", heading: "Cadeia de inject", body: "Sequência forense clássica:\n1. Event 1 — loader create\n2. Event 11 — drop DLL\n3. Event 8 — CreateRemoteThread no emulador\n4. Event 5 — loader terminate\n\nCada evento com horário. Chain = BAN." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Montar Chain", body: "Export Sysmon 1, 11, 8, 5 do período.\n\nOrdena cronológico.\n\n14:30 E1 loader\n14:30 E11 inject.dll\n14:31 E8 → HD-Player\n14:32 E5 loader exit" },
      { kind: "tecnica", heading: "📋 Print Cada Event", body: "Print de cada evento com campos visíveis.\n\nSHA dos arquivos (loader, inject.dll).\n\nTarget process no Event 8 = emulador." },
      { kind: "tecnica", heading: "⚖️ Veredito BAN", body: "Chain completa = evidência forte única.\n\nStaff não questiona. 4 eventos, 4 prints, SHA anexo.", example: "Mano, cadeia completa: loader 14:30, drop 14:30, inject HD-Player 14:31, exit 14:32. Não tem 'talvez'. BAN." },
      { kind: "veredito", heading: "Chain no Relatório", body: "EVIDÊNCIA #1-4: cada evento numerado.\n\nTimeline visual. VEREDITO: BAN." },
    ],
    ["Montar chain 1→11→8→5", "Print cada event", "SHA arquivos", "Target emulador", "Veredito BAN"]),
  L("det-driver-kernel", "Detecção: Driver Kernel Não Assinado", "deteccoes",
    "Kernel cheat carrega driver sem Authenticode. System Informer → Drivers. Unsigned + nome random = BAN kernel.",
    [
      { kind: "intro", heading: "Driver kernel", body: "Cheat kernel mode = driver .sys carregado.\n\nSem assinatura Authenticode.\n\nNome aleatório: x7k2.sys, msagent28.sys." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — SI Drivers", body: "System Informer → System → Drivers.\n\nOrdena por Load time.\n\nProcura: unsigned, nome random, load time vs jogo." },
      { kind: "tecnica", heading: "🚗 Unsigned + Random", body: "Driver: x7k2.sys — unsigned — loaded 14:00\n\nLoad time minutos antes do emulador.\n\nScan kernel flags no 171 ScreenS.", example: "Irmão, driver x7k2.sys unsigned carregado 14:00. Não é driver da NVIDIA não. Kernel cheat. BAN." },
      { kind: "tecnica", heading: "🔗 bcdedit + Secure Boot", body: "testsigning Yes facilita load.\n\nSecure Boot off.\n\nCombo kernel documentado." },
      { kind: "veredito", heading: "Driver no Veredito", body: "Unsigned driver + load time = BAN kernel.\n\nPrint SI Drivers. Escalar se minifilter." },
    ],
    ["List drivers SI", "Assinatura", "Load time", "Scan kernel flags", "bcdedit"]),
  L("det-timeline-pro", "Detecção: Timeline Forense Pro", "deteccoes",
    "Prefetch + Journal + Sysmon + Event em uma linha. Gap suspeito = delete antes scan. Timeline mata veredito.",
    [
      { kind: "intro", heading: "Timeline unificada", body: "Planilha ou doc: HH:MM | Fonte | Ação | Evidência.\n\nFontes: Prefetch, Journal, Sysmon, Event Viewer, scan.\n\nGap = período sem logs ou delete mass antes scan." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Coletar Fontes", body: "1. Prefetch — execuções\n2. Journal — create/delete/rename\n3. Sysmon — 1,3,8,10,11,22\n4. Event — 1000, 4104, 104, 1102\n5. Scan 171 ScreenS — timestamp\n\nExporta tudo. Ordena cronológico." },
      { kind: "tecnica", heading: "🕳️ Gap Suspeito", body: "14:25 CCleaner exec\n14:28 200 deletes Journal\n14:35 scan clean\n\nGap 14:28-14:35 = limpou antes telagem.", example: "Mano, timeline: CCleaner 14:25, 200 deletes 14:28, scan 14:35 limpo. Tu limpou ou tu limpou?" },
      { kind: "tecnica", heading: "📊 Export PDF", body: "Timeline visual pro staff.\n\nMarca gaps em vermelho.\n\nCada linha com print reference." },
      { kind: "veredito", heading: "Timeline no Veredito", body: "Timeline completa = staff aceita.\n\nGap + anti-forense = SUSPEITO/BAN.\n\nAnexa PDF." },
    ],
    ["Coletar todas fontes", "Ordenar cronológico", "Marcar gaps", "Timeline visual", "Export PDF"]),
  L("det-relatorio-pro", "Relatório Profissional de Telagem", "deteccoes",
    "Template que staff aceita sem retrabalho. Resumo → evidências numeradas → veredito. Linguagem clara, SHA anexo.",
    [
      { kind: "intro", heading: "Relatório pro", body: "Staff odeia relatório bagunçado.\n\nEstrutura fixa: 1.Resumo 2.Dados pin 3.Evidências numeradas 4.Veredito 5.Anexos SHA/prints." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Template", body: "RESUMO: 2-3 linhas — user, motivo, veredito.\n\nDADOS: pin 171 ScreenS, data/hora SS, emulador.\n\nEVIDÊNCIA #1, #2, #3 — cada uma: fonte, horário, print ref.\n\nVEREDITO: CLEAN/SUSPEITO/BAN.\n\nANEXOS: SHA256 dos binários, prints datados." },
      { kind: "tecnica", heading: "📝 Exemplo Evidência", body: "EVIDÊNCIA #1: Event 8 CreateRemoteThread — HD-Player.exe — 14:31 — Print anexo A\nEVIDÊNCIA #2: Prefetch LOADER.EXE — 14:30 — Print anexo B\nVEREDITO: BAN — 2 evidências independentes", example: "Relatório neutro na call: 'Documentei Event 8 no emulador 14:31 e Prefetch loader 14:30. Veredito BAN.'" },
      { kind: "tecnica", heading: "🖼️ Prints Datados", body: "Todo print com data/hora visível (taskbar ou overlay).\n\nSHA: certutil -hashfile arquivo SHA256.\n\nLinguagem neutra — fatos, não insultos no doc." },
      { kind: "veredito", heading: "Relatório Fechado", body: "Template fixo = zero retrabalho staff.\n\nRecomendação rescan se suspeito sem ban." },
    ],
    ["Template fixo", "SHA em anexo", "Prints datados", "Evidências numeradas", "Linguagem neutra"]),
  L("det-falso-positivo", "Evitar Falso Positivo", "deteccoes",
    "Unsigned alone, VT clean, um serviço off legítimo — NÃO banir. Mínimo 2 evidências ou 1 forte. Telador pro não expõe.",
    [
      { kind: "intro", heading: "FP = exposed", body: "Banir por unsigned DLL em Temp sem execução = FP.\n\nVT 0/72 = cheat privado comum.\n\nUm serviço off (DiagTrack) = pode ser otimização legítima.\n\nRegra: 2 evidências independentes OU 1 evidência forte (Event 8/10 + emulador)." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Regra de Evidência", body: "Forte sozinha: Event 8 inject emulador, Event 10 ALL_ACCESS + overlay, chain 1→11→8.\n\nFraca sozinha: unsigned Temp, VT 2/72 heuristic, SysMain off.\n\nCombo 2 fracas = suspeito. 1 forte = ban." },
      { kind: "tecnica", heading: "⚠️ Investigar, Não Banir", body: "Só unsigned DLL em Temp sem execução = investigar.\n\nContexto user: dev? modder? dual boot?\n\nRegra servidor: mínimo evidências?", example: "Na call: 'Achamos unsigned em Temp mas zero execução. Suspeito, não ban. Recomendo rescan.'" },
      { kind: "tecnica", heading: "👥 Segunda Opinião", body: "Dúvida = escala staff.\n\nDump, timeline, segunda SS.\n\nMelhor SUSPEITO que BAN errado." },
      { kind: "veredito", heading: "FP Evitado", body: "2 evidências? Contexto ok? Regra servidor?\n\nDocumenta por que SUSPEITO e não BAN." },
    ],
    ["2 evidências?", "Contexto user", "Regra servidor", "Segunda opinião", "SUSPEITO vs BAN"]),
  L("det-uefi-scan", "Detecção: UEFI no 171 ScreenS", "deteccoes",
    "Flags UEFI do scanner + msinfo32 Secure Boot off = escalar. Não ban só por flag — correlaciona.",
    [
      { kind: "intro", heading: "UEFI no scan", body: "171 ScreenS — área UEFI/Secure Boot.\n\nFlags: anomaly, bootkit suspect, ESP modification.\n\nCorrelaciona msinfo32 + ESP listing." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Painel UEFI", body: "Scan result — seção UEFI.\n\nAnota flags.\n\nmsinfo32 Secure Boot State.\n\nESP check se possível." },
      { kind: "tecnica", heading: "🚨 Flag + Secure Boot Off", body: "Scan: UEFI anomaly\nSecure Boot: OFF\nCompetitive emu\n\n= Escalar Tier II investigação.", example: "Scan UEFI anomaly + Secure Boot off. Não ban direto — ESP check + bcdedit. Escalar se bootkit." },
      { kind: "veredito", heading: "UEFI Escalar", body: "Flag sozinha = indicio. Flag + ESP + off = escalar Tier III.\n\nDocumenta scan + msinfo32." },
    ],
    ["Scan UEFI", "msinfo32", "ESP check", "Escalar se bootkit", "Documentar"]),
  L("det-remote-scan", "Detecção: Remote no Scanner", "deteccoes",
    "AnyDesk, Parsec, RustDesk ativo na SS — muitos servidores = ban automático remote. Documenta sessão.",
    [
      { kind: "intro", heading: "REMOTE no 171 ScreenS", body: "Área REMOTE — AnyDesk, Parsec, RustDesk, TeamViewer.\n\nSessão ativa = alguém controlando PC.\n\nRegra servidor: remote = ban automático em SS." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Área REMOTE", body: "Scan result — REMOTE section.\n\nAtivo? Qual software?\n\nSessão em andamento = documenta IP se visível." },
      { kind: "tecnica", heading: "📋 Regra Servidor", body: "Muitos servidores: remote em SS = BAN.\n\nUser: 'trabalho' — regra é regra.\n\nPrint REMOTE ativo + timestamp.", example: "REMOTE: AnyDesk active session. Regra servidor = BAN remote em SS. Trabalho ou não, regra manda." },
      { kind: "veredito", heading: "Remote Veredito", body: "Ativo + regra = BAN.\n\nInativo mas instalado = nota no relatório.\n\nTier III: remote deep bypass." },
    ],
    ["Área REMOTE scan", "Sessão ativa?", "Regra servidor", "Print", "Documentar"]),
  L("det-external-memory", "Detecção: External Memory Read", "deteccoes",
    "Event 10 + overlay + leitura constante + sem DLL no emu = external aimbot clássico. Combo que mata.",
    [
      { kind: "intro", heading: "External pattern", body: "Cheat external: processo separado lê memória do emulador.\n\nEvent 10 ProcessAccess — GrantedAccess ALL_ACCESS.\n\nOverlay topmost. Sem DLL inject no emu às vezes." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Combo External", body: "1. Event 10 — Source cheat.exe → Target HD-Player — 0x1F0FFF\n2. System Informer — overlay.exe topmost\n3. Handles — cheat → emulador\n4. Sem Event 8 às vezes (read only)" },
      { kind: "tecnica", heading: "🎯 Aimbot External", body: "Leitura constante, overlay transparente.\n\nAuth loader separado.\n\nComportamento in-game + evidência = BAN.", example: "cheat.exe Event 10 ALL_ACCESS HD-Player, overlay topmost. External aimbot. BAN." },
      { kind: "veredito", heading: "External Veredito", body: "Event 10 + overlay + GrantedAccess = evidência forte.\n\nDocumenta Source, Target, Access." },
    ],
    ["Event 10 emulador", "Overlay SI", "GrantedAccess", "Comportamento in-game", "Veredito"]),
  L("det-fileless-intro", "Detecção: Fileless (Intro)", "deteccoes",
    "Cheat sem .exe no disco — cmd/ps/python. Prefetch + 4104 + strings memória. Tier III aprofunda.",
    [
      { kind: "intro", heading: "Fileless intro", body: "Sem .exe persistente — script PowerShell, cmd, python.\n\nPrefetch cmd/ps + Event 4104 + scan strings memória.\n\nTier III aprofunda." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Sinais", body: "Prefetch POWERSHELL.EXE ou CMD.EXE minutos antes jogo.\n\n4104: -enc, IEX, DownloadString.\n\nScan: cheat strings em memória, disco limpo." },
      { kind: "tecnica", heading: "📜 PowerShell Cradle", body: "powershell -enc ...\n4104: download cradle\nMemória: auth strings\n\nFileless loader documentado.", example: "Prefetch ps 14:29, 4104 IEX DownloadString, scan strings memória. Fileless. Escalar Tier III." },
      { kind: "veredito", heading: "Fileless Escalar", body: "Sinais fileless = SUSPEITO forte.\n\nEscalar Tier III se confirmado.\n\nDocumenta 4104 + Prefetch." },
    ],
    ["Prefetch ps/cmd", "4104", "Memória strings", "Disco limpo", "Escalar Tier III"]),
  L("det-hollowing-intro", "Detecção: Process Hollowing (Intro)", "deteccoes",
    "Processo legítimo com código substituído — svchost path OK, memória unsigned. Tier III confirma.",
    [
      { kind: "intro", heading: "Hollowing intro", body: "Process hollowing: exe legítimo (svchost, notepad) com código malicioso na memória.\n\nImage path OK, memória unsigned.\n\nPPID estranho, Event 8 self-inject pattern." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Sinais", body: "System Informer — processo legítimo, memory unsigned.\n\nPPID não bate com parent esperado.\n\nEvent 8 pattern suspeito." },
      { kind: "tecnica", heading: "👻 Svchost Falso", body: "svchost.exe path C:\\Windows\\System32\\svchost.exe\nSI: memory unsigned, thread start suspeito\n\nHollow clássico.", example: "svchost path OK mas memória unsigned. Tu hollowing ou tu hollowed?" },
      { kind: "veredito", heading: "Hollow Escalar", body: "Sinais hollowing = escalar Tier III.\n\nNão ban só por unsigned memory — confirma." },
    ],
    ["SI memory unsigned", "PPID", "Event 8", "Escalar Tier III", "Documentar"]),
  L("det-forense-combo", "Detecção: Combo Forense Avançado", "deteccoes",
    "Scan suspeito disco limpo — dump + journal delete + Event 3 auth. Combo memória + anti-forense = BAN composto.",
    [
      { kind: "intro", heading: "Combo forense", body: "Disco limpo mas scan suspeito.\n\nDump: auth strings.\n\nJournal: delete 14:28.\n\nEvent 3: auth IP.\n\n= BAN memória + anti-forense." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Cenário", body: "1. Scan base — flags, strings\n2. Disco — Prefetch/Temp limpos\n3. Memória — dump strings\n4. Journal — delete mass\n5. Sysmon — Event 3 auth" },
      { kind: "tecnica", heading: "🔗 Veredito Composto", body: "Cada fonte fraca sozinha. Juntas = BAN.\n\nDisco limpo + dump auth + delete = xiter limpou e esqueceu RAM.", example: "Disco limpo, dump licenseauth, journal 200 deletes 14:28. BAN composto." },
      { kind: "veredito", heading: "Combo Documentado", body: "Lista cada fonte como evidência numerada.\n\nVeredito composto explícito." },
    ],
    ["Scan base", "Dump memória", "Journal delete", "Event 3 auth", "Veredito composto"]),
  L("det-emulador-specific", "Detecção: Emulador Específico", "deteccoes",
    "BlueStacks, LDPlayer, MSI — processo principal diferente. Inject no Player, não no Agent. Telador burro erra o processo.",
    [
      { kind: "intro", heading: "Emuladores", body: "BlueStacks: HD-Player.exe + HD-Agent.exe — inject no Player.\n\nLDPlayer: LdVBoxHeadless, dnplayer.\n\nMEmu: MEmu.exe.\n\nDLL inject sempre no processo principal do jogo." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Identificar Emu", body: "Pergunta qual emulador.\n\nProcesso principal — onde jogo roda.\n\nEvent 8 Target = processo correto.\n\nSI — DLL list no processo certo." },
      { kind: "tecnica", heading: "🎮 BlueStacks", body: "HD-Player.exe = principal.\nHD-Agent.exe = serviço.\n\nInject no Player. Agent sem DLL suspeita = normal.", example: "Inject no HD-Player, não Agent. Event 8 target Player = correto." },
      { kind: "veredito", heading: "Emu no Relatório", body: "Identifica emu + processo principal.\n\nEvent target correto.\n\nDLL list documentada." },
    ],
    ["Identificar emu", "Processo principal", "DLL list SI", "Event 8 target", "Relatório"]),
  L("det-auth-custom", "Detecção: Auth Custom Privado", "deteccoes",
    "Auth que não é KeyAuth — panels próprios, XOR URLs. Event 3+22 + dump strings = hunt privado.",
    [
      { kind: "intro", heading: "Auth privado", body: "Não está em listas públicas.\n\nEvent 3 IP desconhecido, Event 22 DNS random.\n\nStrings XOR no dump. DIE no loader." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Hunt Privado", body: "Event 3 — IPs não conhecidos.\nEvent 22 — api.x7k2-private.net\nDump — strings decode\nDIE — packer no loader" },
      { kind: "tecnica", heading: "🔍 DNS Random", body: "QueryName não em threat intel.\n\nLoader conecta IP único.\n\nCheat privado = VT 0/72.", example: "DNS api.x7k2-private.net, IP desconhecido, dump strings auth. Privado. Documenta." },
      { kind: "veredito", heading: "Privado Documentado", body: "Event 3+22 + dump = evidência.\n\nNão ban só por IP unknown — combo exec." },
    ],
    ["Event 3+22", "Dump strings", "DIE loader", "VT context", "Documentar"]),
  L("det-servicos-combo", "Detecção: Combo 5+ Serviços", "deteccoes",
    "Script bypass desliga pacote: SysMain, EventLog, Defender, Dnscache, DiagTrack, Sysmon. 3+ off = crítico.",
    [
      { kind: "intro", heading: "Combo serviços", body: "SysMain, EventLog, Defender, Dnscache, DiagTrack, Sysmon — 3+ Disabled/Stopped = crítico.\n\n5+ off + prefetch vazio = script bypass." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Contar Off", body: "services.msc — lista status.\n\nConta Disabled/Stopped.\n\n3+ = suspeito. 5+ = crítico.\n\nPrefetch script otimizar.bat?" },
      { kind: "tecnica", heading: "📜 Script Bypass", body: "5 serviços OFF + prefetch vazio + journal delete.\n\n= Script bypass/optimizer.", example: "5 serviços forense off, prefetch 3 arquivos. Script bypass. BAN/SUSPEITO forte." },
      { kind: "veredito", heading: "Combo Serviços", body: "Lista serviços off no relatório.\n\nCombo com Prefetch/Journal.\n\nBan se regra + combo crítico." },
    ],
    ["Contar serviços off", "Script Prefetch?", "Journal", "Lista relatório", "Veredito"]),
  L("det-wer-memory", "Detecção: WER + Memory Correlation", "deteccoes",
    "Crashdump + dump ativo = mesma DLL faulting. Event 1000 + WER + dump manual = prova dupla.",
    [
      { kind: "intro", heading: "WER + Memory", body: "Event 1000 faulting inject.dll.\n\nWER ReportArchive dump mesmo crash.\n\nDump manual HD-Player ativo — mesma DLL strings.\n\nProva dupla." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — Correlacionar", body: "1. Event 1000 — faulting module\n2. WER folder — dump do crash\n3. Dump manual — se processo ainda vivo\n4. SHA DLL — mesma em todos" },
      { kind: "tecnica", heading: "🔗 Mesma DLL", body: "1000 fault inject.dll\nWER dump: inject.dll strings\nDump HD-Player: inject.dll\n\nSHA match = prova dupla.", example: "1000 fault inject.dll, WER e dump manual mesma DLL. Inject confirmado. BAN." },
      { kind: "veredito", heading: "Prova Dupla", body: "1000 + WER + dump = evidência forte.\n\nSHA anexo. Timeline crash." },
    ],
    ["Event 1000", "WER dump", "Dump manual", "SHA DLL", "Timeline"]),
];
