import type { Lesson } from "./types";

const L = (
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ id, title, categoryId, tier: "tier1", intro, sections, checklist });

export const tier1Lessons: Lesson[] = [
  L("prefetch", "Prefetch — Caça ao Xiter", "windows",
    "Seja bem-vindo ao único lugar onde a burrice do usuário de software de terceiro é usada como nossa maior arma.",
    [
      {
        kind: "intro",
        heading: "O que é a Prefetch?",
        body: "O Windows é um sistema preguiçoso. Para abrir os programas mais rápido, ele cria um cache (memória rápida) de tudo que foi executado no PC na pasta:\n\nC:\\Windows\\Prefetch\n\nCada execução gera um arquivo .pf com nome tipo NOME.EXE-HASH.pf. O hash muda se o caminho do .exe mudar — o Windows não se importa com o nome que o xiter colocou.",
      },
      {
        kind: "intro",
        heading: "O erro clássico do xiter",
        body: "O xiter acha que é o Mr. Robot. Baixa o Super-Mega-Ultra-Fire-Bypass-Anti-Tela.exe, renomeia pra calc.exe ou chrome.exe, roda, fecha antes da SS e jura que tá limpo.\n\nO erro dele: o Windows carimba o arquivo com o Hash de Execução e cria o .pf. O rastro fica lá por dias só esperando você passar o rodo.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Invadindo a Pasta",
        body: "Para começar, pede a tela do elemento e manda ele fazer isso:\n\n1. Apertar Win + R\n2. Digitar prefetch e dar Enter\n3. Vai pedir permissão de administrador — manda clicar em Continuar\n\nAgora você está olhando pro cemitério de mentiras dele. Ordena por Data de Modificação (mais recente primeiro).",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. O Golpe do Chrome Reverso",
        body: "O xiter renomeou o cheat pra chrome.exe. Na Prefetch aparece CHROME.EXE-XXXXXX.pf.\n\nComo desmascarar:\n• Chrome real abre vários processos e tem padrão de hash específico\n• .pf de chrome fake costuma ser minúsculo ou executado de Downloads/Temp\n• Cruza com caminho no WinPrefetchView se tiver",
        example: "Ué, meu mano? Desde quando o Google Chrome consome 4MB de RAM, não tem ícone e foi executado de C:\\Users\\User\\Downloads\\Nova_Pasta_3? Você tava pesquisando como ser banido em três idiomas?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. O Paradoxo do Tempo",
        body: "O cara jura que não usa xit faz 3 meses. Você ordena a Prefetch por Data de Modificação.\n\nA análise: o jogo abriu às 21:30. Tem CMD.EXE ou POWERSHELL.EXE modificado às 21:29 — um minuto antes.\n\nIsso não é coincidência. É loader ou script de limpeza.",
        example: "Caraca, que coincidência! Você sentiu vontade incontrolável de abrir o Prompt exatamente UM MINUTO antes do jogo? Deixa eu adivinhar... o script injetou vibe boa no emulador?",
      },
      {
        kind: "tecnica",
        heading: "❌ 3. Excluidores de Rastro",
        body: "Loaders tentam limpar Prefetch ao fechar (del /f /q).\n\nO sintoma: pasta com 5 arquivos .pf num PC usado todo dia.\n\nA realidade: ninguém usa Windows sem acumular dezenas de .pf em poucas horas. Prefetch limpa demais = anti-forense = suspeito.",
        example: "Rapaz, seu Windows é diferenciado né? Limpinho assim... Ou comprou o PC na vitrine faz 5 minutos, ou o xit tentou apagar prova e te entregou de bandeja.",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 4. O Hash Não Mente",
        body: "Cada .pf termina com código de 8 caracteres (ex: NOTEPAD.EXE-A1B2C3D4.pf). Gerado pelo caminho original do executável.\n\nCalculadora do System32 = um hash. Calculadora clonada em Downloads = outro hash.\n\nLoader disfarçado sempre entrega o caminho real no nome do .pf.",
        example: "Mano, que calculadora gamer é essa executada direto da pasta Downloads? Tava fazendo conta de quantos abates ia dar de parede?",
      },
      {
        kind: "veredito",
        heading: "📚 MÓDULO 4 — O Gran Finale",
        body: "Depois de achar incompatibilidade de horário, executável disfarçado ou pasta suspeita:\n\n• Não aceita \"é script de otimizar ping do meu primo\"\n• Documenta com print datado\n• Cruza com 171 ScreenS + Journal se tiver\n• Veredito na call: evidência + horário + artefato\n\nStatus: Graduado em Humilhação de Xiter. Pode puxar a próxima tela.",
      },
    ],
    [
      "Pedir Win+R → prefetch → Continuar",
      "Ordenar por Data de Modificação",
      "Procurar .exe disfarçado (chrome, calc, notepad fora do lugar)",
      "Verificar se pasta está vazia demais (anti-forense)",
      "Cruzar horário cmd/powershell com abertura do jogo",
      "Print datado + veredito",
    ]),
  L("temp-recent", "Temp · Recent · AppData — O Esconderijo Burro", "windows",
    "O xiter limpa Prefetch mas esquece que o Windows guarda o lixo dele em Temp, Recent e AppData. É tipo limpar a sala e deixar o corpo no armário.",
    [
      { kind: "intro", heading: "Por que isso importa?", body: "99% dos cheaters apagam o .exe mas esquecem:\n• %TEMP% — loaders e .dll\n• Recent — atalhos .lnk de arquivos abertos\n• AppData — configs de auth e pastas com nome de bot\n\nTelador que só olha Prefetch perde metade do mapa." },
      { kind: "modulo", heading: "📚 MÓDULO 1 — %TEMP%", body: "Na SS manda o cara:\n\n1. Win + R\n2. Digita %temp% e Enter\n3. Clica na coluna Data e ordena do mais recente pro mais antigo\n\nProcura: .exe, .dll, .bat, nomes aleatórios (a8f2k.exe, svc_host.exe), pasta criada hoje." },
      { kind: "tecnica", heading: "🕵️ Loader no Temp", body: "Padrão clássico: baixou loader, executou de Temp, 'deletou' o arquivo mas o journal/prefetch/recent ainda fala.\n\nManda procurar arquivo modificado minutos antes do jogo ou da SS.", example: "Irmão, esse svchost_update.exe de 890KB no Temp não é do Windows não. O svchost original não mora aí. Explica essa visita?" },
      { kind: "modulo", heading: "📚 MÓDULO 2 — Recent (.lnk)", body: "Win + R → shell:recent → Enter\n\nMostra atalhos de tudo que ele abriu. Mesmo se deletou o .exe, o .lnk pode apontar pro caminho real.\n\nClica direito no .lnk suspeito → Propriedades → vê o destino." },
      { kind: "modulo", heading: "📚 MÓDULO 3 — AppData", body: "Win + R → %appdata% e %localappdata%\n\nPastas com nome random (x7k2m, a8f2k9), arquivos .json com key/license, .dll escondida.\n\nCheater de auth deixa config do painel aqui." },
      { kind: "veredito", heading: "Fechando a telagem", body: "Temp + Recent + AppData sozinhos raramente são ban automático — mas com Prefetch/scan batendo horário vira prova.\n\nPrint de cada pasta com data visível. Anota caminho completo." },
    ], ["Win+R %temp% ordenar por data", "Win+R shell:recent checar .lnk", "Varrer AppData pastas random", "DIE+SHA em .exe achado", "Print datado", "Cruzar com Prefetch/scan"]),
  L("uso-dados", "Uso de Dados — O Contador de Mentiras", "windows",
    "O xiter acha que apagou tudo, mas o Windows anotou cada MB que o loader mandou pro servidor de auth. Contador de internet não mente — só o usuário.",
    [
      {
        kind: "intro",
        heading: "O que é Uso de Dados?",
        body: "Windows 10/11 guarda quanto cada app consumiu de internet nos últimos 30 dias.\n\nAuth online, phone-home de loader, painel de cheat — tudo que fala com servidor externo deixa rastro aqui. O xiter limpa Prefetch mas esquece que o Windows já contabilizou o tráfego.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Abrindo o Contador",
        body: "Na SS manda ele abrir:\n\n1. Configurações (Win + I)\n2. Rede e Internet → Uso de dados\n3. Clica em \"Ver uso por aplicativo\"\n4. Filtra últimos 7 ou 30 dias\n\nPedir print com data visível. Ordena por consumo — quem come mais MB aparece primeiro.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. App Fantasma com Tráfego",
        body: "Red flags clássicas:\n• .exe com nome genérico (Host.exe, Service.exe, RuntimeBroker_fake)\n• Executável em Temp/Downloads consumindo dezenas de MB\n• App que o user \"nunca viu\" com tráfego constante\n\nCruza o nome com Prefetch e scan 171 ScreenS.",
        example: "Mano, esse Loader_v2.exe de 45MB nos últimos 7 dias... tu tava baixando wallpaper ou validando key de cheat? Porque RuntimeBroker legítimo não mora em Temp.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Horário Bate com Auth",
        body: "Loader de auth faz phone-home toda vez que abre.\n\nSe o tráfego do .exe suspeito coincide com horário do ban ou abertura do emulador — não é coincidência.\n\nInternal cheat consome pouco. Loader/auth consome MUITO. Foca no .exe estranho com MB alto.",
        example: "Caraca, coincidência de novo né? O unknown.exe gastou 12MB exatamente na hora que tu abriu o emulador. Que sorte, hein?",
      },
      {
        kind: "zuera",
        heading: "💸 3. Internal vs Loader — Não Confunde",
        body: "Cheater burro acha que \"internal não usa internet\" = clean.\n\nInternal injeta local, mas o LOADER que baixou e autenticou já deixou rastro aqui.\n\nUso de dados pega o loader, não o inject. Mesmo assim é prova.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Uso de Dados",
        body: "Sozinho raramente é ban automático — mas .exe suspeito + tráfego alto + Prefetch = evidência forte.\n\nDocumenta: nome do app, MB consumidos, período, print datado.\n\nCruza com scan strings (KeyAuth, license URLs).",
      },
    ],
    [
      "Configurações → Uso de dados → Ver por app",
      "Filtrar últimos 7 dias",
      "Anotar apps desconhecidos com tráfego alto",
      "Cruzar nome com Prefetch/scan",
      "Print com data visível",
      "Timeline tráfego vs abertura emulador",
    ]),
  L("antivirus", "Antivírus & Defender — O Confessionário", "windows",
    "O Defender detectou o cheat, o xiter restaurou da quarentena e acha que ninguém viu. Histórico de proteção é o confessionário digital dele.",
    [
      {
        kind: "intro",
        heading: "Por que o AV importa na telagem?",
        body: "Segurança do Windows registra TUDO: detecções, quarentenas, restaurações pelo usuário, exclusões manuais.\n\nCheater clássico: exclui pasta do cheat do scan OU desliga Defender OR restaura Trojan da quarentena. Cada ação fica logada.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Histórico de Proteção",
        body: "Caminho na SS:\n\n1. Segurança do Windows\n2. Proteção contra vírus e ameaças\n3. Histórico de proteção\n\nProcura: detecções de cheat, Trojan, HackTool, PUA. Olha se status é Quarentenado, Removido ou RESTAURADO PELO USUÁRIO.",
        example: "Irmão, Trojan:Win32/CheatGen foi detectado, colocado em quarentena e VOCÊ restaurou. Tu restaurou vírus achando que era presente de aniversário?",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Exclusões — Red Flag Absoluta",
        body: "Gerenciar configurações → Exclusões.\n\nPasta excluída tipo C:\\cheats, C:\\Users\\X\\AppData\\Local\\a8f2k, ou Temp inteiro = o cara SABE o que tem lá.\n\nNinguém exclui pasta random por \"otimização\".",
        example: "Ué, por que C:\\Users\\User\\AppData\\Local\\cheat tá excluído do Defender? Nome da pasta já entrega, mano.",
      },
      {
        kind: "tecnica",
        heading: "❌ 2. Tampering — Defender OFF",
        body: "Sinais de bypass:\n• Proteção em tempo real desativada\n• Serviço WinDefend parado\n• Tamper Protection off sem motivo\n\n171 ScreenS já lista isso no painel. Pergunta na call — resposta \"sempre foi assim\" = mentira.",
        example: "Defender off, Tamper Protection off, serviço parado... PC de vitrine ou tu desligou pra rodar xit em paz?",
      },
      {
        kind: "zuera",
        heading: "🛠️ 3. Restaurar ≠ Apagar Histórico",
        body: "Xiter inteligente restaura da quarentena e deleta o .exe achando que limpou.\n\nO HISTÓRICO continua lá: \"Usuário permitiu ameaça\". Game over.\n\nPrint datado do histórico vale mais que argumento na call.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Defender",
        body: "Detecção restaurada = ban justificado na maioria dos casos.\nExclusão de pasta suspeita = SUSPEITO forte mínimo.\nDefender off + outras evidências = tampering documentado.\n\nPrint de histórico + exclusões + status do serviço.",
      },
    ],
    [
      "Abrir Histórico de proteção",
      "Procurar detecções restauradas pelo usuário",
      "Listar exclusões de pastas",
      "Verificar Defender ativo (171 ScreenS)",
      "Print datado de cada achado",
      "Cruzar detecção com Prefetch do mesmo .exe",
    ]),
  L("journal-trace", "Journal Trace (USN) — O Diário Secreto", "bypass",
    "O xiter deletou Prefetch, Temp e logs achando que sumiu. O USN Journal anotou cada DELETE como se fosse câmera de segurança. Bem-vindo ao diário que ele esqueceu.",
    [
      {
        kind: "intro",
        heading: "O que é USN Journal?",
        body: "Update Sequence Number — log nativo do NTFS que registra CREATE, DELETE, RENAME, MODIFY em arquivos e pastas.\n\nQuem limpa evidência antes da SS deixa spike de deletes aqui. Ferramentas: MFTECmd, JournalTrace, ou área USN do 171 ScreenS.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Exportando o Journal",
        body: "Se tiver 171 ScreenS com USN: exporta do período do ban (24-48h antes).\n\nSem ferramenta: pede pro user NÃO mexer e usa o que o scan/export trouxer.\n\nFiltra por: DELETE, RENAME, paths em Prefetch\\Temp\\Logs.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Delete em Massa",
        body: "Centenas de DELETE em Prefetch/Temp/Logs em poucos minutos = limpeza coordenada antes da telagem.\n\nTimeline clássica:\n14:28 — DELETE prefetch\\LOADER*.pf\n14:28 — DELETE 47 arquivos em Temp\n14:30 — Scan iniciado\n\nScript de bypass ou cleaner rodou.",
        example: "Rapaz, 183 deletes em 2 minutos na pasta Prefetch... tu tava organizando arquivo ou apagando prova antes da SS?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Rename Trick",
        body: "Xiter renomeia cheat.exe → notepad.exe achando que engana.\n\nJournal mostra RENAME com caminho original e novo.\n\nPrefetch pode ter hash novo, mas USN guarda a operação de rename.",
        example: "Olha só: RENAME de SuperCheat.exe pra NOTEPAD.EXE às 14:26. Desde quando notepad vem de Downloads?",
      },
      {
        kind: "zuera",
        heading: "❌ 3. Journal Limpo = Journal Limpo",
        body: "Alguns bypass tentam truncar o USN Journal. Isso também é evidência.\n\nJournal vazio ou muito curto em PC ativo = anti-forense avançado.\n\nDocumenta e classifica SUSPEITO/BAN conforme combo de indícios.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — USN",
        body: "Spike DELETE + horário antes do scan = evidência forte de limpeza.\nRENAME de .exe suspeito = prova de disfarce.\n\nMonta timeline: delete → rename → scan. Print/export datado no relatório.",
      },
    ],
    [
      "Exportar journal do período (24-48h)",
      "Filtrar DELETE em massa em Prefetch/Temp",
      "Procurar RENAME de .exe suspeitos",
      "Montar timeline delete → scan",
      "Documentar spike de deletes",
      "Cruzar com Prefetch vazio se tiver",
    ]),
  L("delete-mass", "Delete & Limpeza — O Modo Pânico", "bypass",
    "Bypass genérico quase sempre deleta algo antes da SS. Prefetch vazio, Temp limpo, logs apagados — é o modo pânico do xiter virando evidência contra ele.",
    [
      {
        kind: "intro",
        heading: "Por que delete importa?",
        body: "Cheater com bypass roda script de limpeza: del Prefetch, del Temp, esvazia lixeira, limpa Event Log.\n\nCada ação deixa rastro — USN Journal, .pf de cleaner, Event 1102.\n\nPC \"limpo demais\" num dia de SS = suspeito, não inocente.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Sinais de Limpeza",
        body: "Checklist visual na SS:\n• Prefetch com menos de 5 .pf em PC usado todo dia\n• %TEMP% vazio ou só arquivos antigos\n• Event Viewer sem entradas recentes\n• Lixeira esvaziada no horário do ban\n• USN com spike de DELETE\n\nUm sinal = olho aberto. Três = modo pânico confirmado.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Cleaners — CCleaner, BleachBit, PrivaZer",
        body: "Cleaner deixa .pf na Prefetch (CCleaner.exe-*.pf) e centenas de deletes no journal.\n\nScan pode dar CLEAN em strings, mas anti-forense está documentado.\n\nPergunta na call: \"Tu rodou CCleaner hoje?\" — hesitação = bingo.",
        example: "CCleaner às 14:25, 200 deletes no journal, Prefetch com 3 arquivos... scan clean mas tu limpou prova na cara dura.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Horário Delete vs Scan",
        body: "Monta timeline:\n• Hora do ban/aviso\n• Hora de deletes em massa (USN)\n• Hora que scan/telagem iniciou\n\nGap de minutos entre limpeza e SS = clássico \"fechei o cheat e limpei\".",
        example: "Limpou Prefetch 14:28, AnyDesk abriu 14:30. Que coincidência maravilhosa, hein campeão?",
      },
      {
        kind: "zuera",
        heading: "❌ 3. Limpeza Manual ≠ Uso Normal",
        body: "User comum não esvazia lixeira, Prefetch e Temp no mesmo minuto.\n\nSeparar: manutenção ocasional vs padrão de anti-forense antes de telagem.\n\nContexto + horário + quantidade de deletes = veredito.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Delete & Limpeza",
        body: "Anti-forense documentada = SUSPEITO mínimo, BAN se combo com auth/inject/delete mass.\n\nRelatório: lista o que foi deletado, quando, quantos arquivos, ferramenta usada.\n\nPrint Prefetch vazio + journal + horário.",
      },
    ],
    [
      "Verificar integridade Prefetch/Temp",
      "Procurar .pf de CCleaner/BleachBit na Prefetch",
      "Exportar USN e contar deletes no período",
      "Montar timeline delete vs início scan",
      "Perguntar sobre limpeza recente na call",
      "Documentar no relatório com prints",
    ]),
  L("bypass-lento", "Lentidão de Bypass — PC de Cartão Postal", "bypass",
    "Bypass mal feito deixa o PC lento que nem internet discada. Boot demorado, emulador travando, serviços desligados — o xiter pagou caro pra se entregar.",
    [
      {
        kind: "intro",
        heading: "Por que bypass lento denuncia?",
        body: "Bypass genérico desliga serviços, injeta drivers kernel, mata processos do Windows.\n\nResultado: boot 2-3x mais lento, explorer com CPU alta, emulador demorando pra abrir.\n\nUser jura que \"sempre foi assim\" — mentira. PC normal não fica nesse estado.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Sinais na Call",
        body: "Observa durante a SS:\n• Demora pra abrir pastas/prefetch\n• Emulador lento ou crashando\n• Explorer.exe com CPU alta no Task Manager\n• Boot lento (pergunta quanto tempo demora)\n\n171 ScreenS lista serviços off — usa como mapa.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Combo Serviços OFF",
        body: "Bypass clássico desliga:\n• SysMain (Prefetch)\n• EventLog\n• WSearch\n• WinDefend\n\nTrês ou mais off sem motivo legítimo = tampering. Pergunta na call — resposta vaga = suspeito.",
        example: "SysMain off, EventLog off, Defender off... tu desligou metade do Windows pra rodar xit ou o PC veio assim da fábrica?",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. Drivers Kernel Não Assinados",
        body: "System Informer → Drivers. Driver sem assinatura Microsoft carregado = bypass kernel ou rootkit.\n\nCorrelaciona com lentidão e serviços off.\n\nPrint driver suspeito + nome + status.",
        example: "Driver 'WinRing0' ou nome random sem assinatura carregado... isso é otimização de FPS ou bypass de kernel?",
      },
      {
        kind: "zuera",
        heading: "🕒 3. Emulador Travando = Inject Pesado",
        body: "Internal mal feito ou external pesado deixa emulador instável.\n\nPergunta: \"Trava desde quando?\" — se coincide com instalação de \"otimizador\", bingo.\n\nLentidão sozinha não bane — mas reforça combo de evidências.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Bypass Lento",
        body: "Serviços off + lentidão + drivers suspeitos = SUSPEITO forte.\n\nDocumenta no painel scan, pergunta na call, correlaciona com Prefetch/journal.\n\nNão bane só por PC lento — usa como reforço.",
      },
    ],
    [
      "Checar serviços no painel 171 ScreenS",
      "Perguntar sobre lentidão/boot na call",
      "System Informer → Drivers não assinados",
      "Correlacionar serviços off com Prefetch vazio",
      "Print status serviços + drivers",
      "Incluir no relatório como indício médio",
    ]),
  L("system-informer-intro", "System Informer — Raio-X do Processo", "ferramentas",
    "Task Manager é brinquedo de criança. System Informer mostra DLLs, handles, threads e rede ao vivo — o raio-X que o xiter não quer que você abra.",
    [
      {
        kind: "intro",
        heading: "O que é System Informer?",
        body: "Sucessor espiritual do Process Hacker. Monitor moderno de processos, serviços, rede e drivers.\n\nNa telagem: vê o que o emulador carregou, quem injetou DLL, quem abriu handle no processo do jogo.\n\nBaixa: systeminformer.sourceforge.io — SEMPRE como admin.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Setup na SS",
        body: "Se já tiver instalado: abre como Administrador.\n\nAbas principais:\n• Processes — lista processos e CPU/RAM\n• Services — serviços Windows\n• Network — conexões ativas por processo\n\nFiltra pelo emulador (HD-Player, BlueStacks, etc).",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. DLLs Não Assinadas",
        body: "Processo do emulador → botão direito → Properties → Modules (ou Memory → Modules).\n\nDLL em C:\\Temp, C:\\Users\\...\\Downloads, sem assinatura Authenticode = material de inject.\n\nPrint módulo + caminho completo.",
        example: "HD-Player.exe carregou unknown.dll de C:\\Temp\\ — sem assinatura, 892KB. Desde quando emulador precisa de DLL random no Temp?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Network Tab — Phone Home",
        body: "Aba Network mostra conexões ativas.\n\nProcesso suspeito conectando IP estranho ou porta não padrão enquanto emulador roda = auth ou external.\n\nCruza com Uso de Dados e scan strings.",
        example: "loader.exe conectado em 185.x.x.x porta 443 enquanto tu jura que não tem nada aberto... explica essa viagem?",
      },
      {
        kind: "zuera",
        heading: "🛠️ 3. Handles e Threads",
        body: "Processo suspeito com handle aberto no HD-Player = external lendo memória.\n\nThreads remotas criadas em processo alheio = inject.\n\nAvançado — tier2 aprofunda. Aqui: print e documenta.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — System Informer",
        body: "DLL unsigned no emulador + caminho Temp = evidência forte.\n\nPrint Modules + Network + processo pai.\n\nSHA256 da DLL suspeita com certutil. Não bane só por DLL system32 legítima.",
      },
    ],
    [
      "Rodar System Informer como admin",
      "Filtrar processo do emulador",
      "Checar Modules — DLLs não assinadas",
      "Aba Network se tráfego estranho",
      "Print caminho completo da DLL suspeita",
      "SHA256 da DLL + cruzar com Prefetch",
    ]),
  L("die", "DIE — Detect It Easy — Autopsia do .exe", "ferramentas",
    "Antes de rodar .exe suspeito na SS, passa no DIE. Packer, entropia e assinatura revelam se é update legítimo ou loader empanado.",
    [
      {
        kind: "intro",
        heading: "O que o DIE faz?",
        body: "Detect It Easy — arrasta .exe e ele cospe: packer (UPX, VMProtect, Themida), .NET vs Native, entropia, compilador, assinatura.\n\nLoader de cheat QUASE SEMPRE vem empacotado. Update.exe legítimo da Microsoft não usa VMProtect.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Scan Básico",
        body: "Na SS quando achar .exe suspeito:\n\n1. Abre DIE (não executa o .exe ainda)\n2. Arrasta o arquivo pro DIE\n3. Lê resultado: packer, entropia, assinatura\n\nEntropia alta (>7.5) + packer conhecido + unsigned = red flag.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Packer de Cheat",
        body: "Packers comuns em loaders:\n• VMProtect, Themida, Enigma\n• UPX (cheat barato)\n• .NET obfuscator\n\nCompare: chrome.exe não vem com VMProtect. update.exe de 890KB com VMProtect 3.x = loader.",
        example: "update.exe — VMProtect 3.x — Entropia 7.8 — Sem assinatura. Mano, isso é update da Adobe ou loader disfarçado?",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. SHA256 com certutil",
        body: "No cmd:\ncertutil -hashfile \"C:\\caminho\\arquivo.exe\" SHA256\n\nHash único no relatório. VirusTotal como referência — NÃO veredito único.\n\n2/72 no VT com contexto Temp + packer = reforço, não condenação isolada.",
        example: "Hash a3f2b1... — VT 2/72 — mas tá em Temp, unsigned, VMProtect. Contexto manda, não só VT.",
      },
      {
        kind: "zuera",
        heading: "❌ 3. Não Executa Antes do DIE",
        body: "Telador amador roda .exe suspeito pra \"ver o que faz\". NÃO.\n\nDIE + SHA primeiro. Executar pode ativar loader, limpar rastros ou piorar situação.\n\nAutopsia antes de ligar o cadáver.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — DIE",
        body: "Packer agressivo + unsigned + Temp/Downloads = evidência concreta.\n\nRelatório: nome, tamanho KB, packer, entropia, SHA256, assinatura sim/não.\n\nCombina com Prefetch, Uso de Dados, scan.",
      },
    ],
    [
      "DIE em todo .exe suspeito antes de executar",
      "Anotar packer e entropia",
      "certutil -hashfile SHA256",
      "Verificar assinatura no DIE",
      "VT como apoio, não veredito único",
      "Print DIE + hash no relatório",
    ]),
  L("event-viewer", "Event Viewer — Logs que o Xiter Esquece", "ferramentas",
    "Event Viewer guarda tudo que o Windows viu. Event 1102 = log limpo — clássico de quem apagou prova minutos antes da SS. Banível em competitive.",
    [
      {
        kind: "intro",
        heading: "Por que abrir Event Viewer?",
        body: "Logs nativos: Security, System, Application, PowerShell Operational.\n\nTelador pro filtra pelo horário do ban e procura IDs críticos.\n\nLog limpo (1102) minutos antes do scan = anti-forense documentada.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Abrindo e Filtrando",
        body: "Na SS:\n\n1. Win + R → eventvwr.msc → Enter\n2. Windows Logs → Security (e System se precisar)\n3. Filtra por horário do ban (Custom Filter ou scroll)\n\nProcura IDs: 1102, 4624, 4625, 4688, 4104 (PowerShell).",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Event 1102 — Log Cleared",
        body: "Security log foi limpo. Quem limpou, quando.\n\nClássico: Administrator limpou log 8 min antes do scan iniciar.\n\nCompetitive: ban justificado na maioria dos casos.",
        example: "Event 1102 às 14:27 — Security log cleared by Administrator. Scan começou 14:35. Limpou prova ou foi manutenção?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Event 4688 — Processo Criado",
        body: "Registra criação de processo se audit policy ativa.\n\nMostra cmd.exe, powershell.exe, loader.exe sendo executados.\n\nCruza horário com Prefetch e journal.",
        example: "4688: powershell.exe criado 14:26, 4688: HD-Player 14:27. Script rodou um minuto antes do jogo de novo?",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 3. PowerShell Operational",
        body: "Applications and Services → Microsoft → Windows → PowerShell → Operational.\n\nEvent 4104 = script block logged. Bypass via PowerShell deixa rastro aqui.\n\nProcura Base64, Invoke-Expression, download strings.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Event Viewer",
        body: "1102 antes do scan = evidência forte anti-forense.\n4688/4104 com loader = timeline de execução.\n\nPrint datado com ID, hora, usuário. Cruza com USN e Prefetch.",
      },
    ],
    [
      "Win+R eventvwr.msc",
      "Filtrar Security pelo horário do ban",
      "Procurar Event 1102 (log cleared)",
      "Checar 4688 processo criado",
      "PowerShell Operational → 4104 se bypass script",
      "Print datado de cada evento crítico",
    ]),
  L("sysmon-event-5", "Sysmon Event 5 — Process Terminated", "sysmon",
    "Sysmon Event 5 registra quando processo morre. Loader fechado segundos antes do AnyDesk abrir? Clássico modo pânico do xiter.",
    [
      {
        kind: "intro",
        heading: "O que é Event 5?",
        body: "Sysmon Event ID 5 = Process Terminated.\n\nRegistra quando um processo encerra: nome, GUID, usuário, horário.\n\nNa telagem: vê o que o cara FECHOU na correria antes de abrir a SS.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Onde Filtrar",
        body: "Event Viewer → Applications and Services Logs → Microsoft → Windows → Sysmon → Operational.\n\nFiltra Event ID 5 no horário do ban (30-60 min antes).\n\nCampos importantes: Image (caminho do .exe), ProcessGuid, User, TimeCreated.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Loader Fechado Antes do Scan",
        body: "Padrão clássico:\n14:34:02 — Event 5: C:\\Temp\\loader.exe terminated\n14:34:30 — AnyDesk/scan iniciado\n\n28 segundos de gap. Fechou o cheat e abriu telagem.\n\nCruza Image com Prefetch e journal.",
        example: "loader.exe terminou 14:34:02, scan 14:34:30. Tu fechou na correria achando que a gente não ia ver?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Múltiplos Terminate em Sequência",
        body: "Vários Event 5 seguidos — loader, injector, cmd — minutos antes da SS.\n\nScript de bypass que mata processos antes de telagem.\n\nTimeline: terminate → terminate → scan.",
        example: "Três processos mortos em 90 segundos antes do AnyDesk... organização de arquivos ou modo pânico?",
      },
      {
        kind: "zuera",
        heading: "❌ 3. Sysmon Não Instalado?",
        body: "Se Sysmon não estiver instalado, Event 5 não existe.\n\nUsa Prefetch, BAM, journal como fallback.\n\n171 ScreenS ou pergunta se servidor competitive exige Sysmon.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Event 5",
        body: "Terminate de .exe suspeito segundos antes do scan = evidência forte.\n\nDocumenta: Image, horário, gap até scan. Print completo do evento.\n\nCombina com Prefetch do mesmo .exe se ainda existir.",
      },
    ],
    [
      "Verificar se Sysmon está instalado",
      "Filtrar Sysmon Operational → Event 5",
      "Procurar terminate minutos antes do scan",
      "Cruzar Image com Prefetch/journal",
      "Documentar gap terminate → scan",
      "Print datado do evento completo",
    ]),
  L("sysmon-event-8", "Sysmon Event 8 — CreateRemoteThread", "sysmon",
    "CreateRemoteThread = injeção DLL no processo alvo. Um dos melhores indicadores de cheat internal. Sysmon não perdoa.",
    [
      {
        kind: "intro",
        heading: "O que é Event 8?",
        body: "Sysmon Event ID 8 = CreateRemoteThread.\n\nProcesso A cria thread remota no processo B = injeção clássica (DLL inject, manual map).\n\nCampos: SourceImage, TargetImage, StartAddress, ThreadId.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Filtrando Event 8",
        body: "Sysmon → Operational → filtra Event ID 8.\n\nFoca TargetImage = emulador (HD-Player.exe, etc).\n\nSourceImage desconhecido + Target = emulador = ban na maioria dos competitive.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Inject no Emulador",
        body: "Exemplo real:\nSourceImage: C:\\Temp\\injector.exe\nTargetImage: C:\\Program Files\\BlueStacks\\HD-Player.exe\n\nInjector desconhecido apontando pro emulador = prova de inject.",
        example: "injector.exe criou thread remota no HD-Player.exe. Tu tava injetando vacina ou cheat?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. StartAddress Suspeito",
        body: "StartAddress fora de módulos legítimos = shellcode ou manual map.\n\nAV e debugger também geram Event 8 — contexto importa.\n\nInjector desconhecido + emulador + horário do ban = veredito claro.",
      },
      {
        kind: "zuera",
        heading: "❌ 3. Falso Positivo",
        body: "Alguns AV, RivaTuner, overlay legítimo geram Event 8.\n\nPergunta na call. Cruza Source com Prefetch/DIE.\n\nSource em Temp unsigned = não é RivaTuner.",
        example: "Source é RivaTuner com assinatura? Ok. Source é a8f2k.exe no Temp? Ban.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Event 8",
        body: "Event 8 com Source suspeito → Target emulador = BAN em competitive.\n\nPrint completo: Source, Target, horário, StartAddress.\n\nHash SHA256 do SourceImage.",
      },
    ],
    [
      "Filtrar Sysmon Event ID 8",
      "TargetImage = emulador?",
      "SourceImage suspeito (Temp, unsigned)?",
      "Print evento completo com horário",
      "SHA256 do SourceImage",
      "Descartar FP conhecido (AV, overlay assinado)",
    ]),
  L("sysmon-event-10", "Sysmon Event 10 — Process Access", "sysmon",
    "OpenProcess com ALL_ACCESS no emulador = cheat external lendo memória. Event 10 entrega o external na bandeja.",
    [
      {
        kind: "intro",
        heading: "O que é Event 10?",
        body: "Sysmon Event ID 10 = Process Access.\n\nProcesso A abre handle no processo B com certo nível de acesso.\n\nCheat external precisa ReadProcessMemory / OpenProcess no emulador — Event 10 registra.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — GrantedAccess",
        body: "Campo GrantedAccess em hex:\n• 0x1F0FFF = PROCESS_ALL_ACCESS\n• 0x1410 = read comum\n\nCheat external pede acesso alto no HD-Player.\n\nFiltra Event 10 onde TargetImage = emulador.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. External Memory Read",
        body: "Exemplo:\nSource: C:\\Users\\X\\Downloads\\cheat.exe\nTarget: HD-Player.exe\nGrantedAccess: 0x1F0FFF\n\nExternal clássico. Print e hash do Source.",
        example: "cheat.exe abriu ALL_ACCESS no HD-Player. Tu tava lendo memória do emulador pra quê? Curiosidade científica?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Cruzar Source com Prefetch",
        body: "SourceImage do Event 10 → busca na Prefetch (.pf), Temp, DIE.\n\nMesmo .exe em múltiplos artefatos = prova consolidada.\n\nTimeline: exec → access → jogo.",
      },
      {
        kind: "zuera",
        heading: "🛠️ 3. CallStack e Source",
        body: "Sysmon avançado loga CallStack. Debuggers legítimos aparecem — contexto de telagem diferencia.\n\ncheat.exe no Downloads ≠ Visual Studio com assinatura.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Event 10",
        body: "ALL_ACCESS no emulador de Source suspeito = BAN competitive.\n\nRelatório: Source, Target, GrantedAccess, horário, SHA256.\n\nCombina com Event 8 se tiver inject também.",
      },
    ],
    [
      "Filtrar Sysmon Event ID 10",
      "TargetImage = emulador",
      "GrantedAccess 0x1F0FFF ou alto",
      "Cruzar SourceImage com Prefetch",
      "certutil -hashfile no Source",
      "Print evento datado completo",
    ]),
  L("exe-suspeito", ".exe Suspeito — KB, SHA, Assinatura", "analise",
    "Achou .exe estranho? Antes de gritar BAN, valida com tamanho, hash e assinatura. Evita ban injusto e fortalece ban justo.",
    [
      {
        kind: "intro",
        heading: "Por que validar binário?",
        body: "Telador amador bane por \"achei estranho\". Telador pro documenta:\n• Tamanho em KB\n• SHA256 único\n• Assinatura Authenticode sim/não\n• Local (Temp, Downloads, System32)\n\nDados concretos no relatório = veredito defensável.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Coleta Básica",
        body: "No .exe suspeito:\n\n1. Propriedades → Detalhes → tamanho\n2. cmd: certutil -hashfile \"caminho\\arquivo.exe\" SHA256\n3. Propriedades → Assinaturas Digitais (ou DIE)\n4. Anota caminho completo e data modificação",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Tamanho Típico de Loader",
        body: "Loaders conhecidos têm faixa de KB (500KB-3MB comum).\n\nCompare com builds documentados internamente.\n\n890KB unsigned em Temp ≠ notepad.exe de 200KB no System32.",
        example: "loader.exe — 1204 KB — Temp — unsigned. Notepad legítimo não tem esse tamanho nem mora aí.",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. SHA256 no Relatório",
        body: "Hash único identifica o binário.\n\nFormato relatório:\narquivo.exe | 1204 KB | SHA256: a3f2b1... | Unsigned | VT 2/72\n\nVT é apoio — contexto manda.",
        example: "Hash a3f2b1c4... bate com loader conhecido da base. Não é 'talvez' — é match.",
      },
      {
        kind: "tecnica",
        heading: "❌ 3. Unsigned + Temp ≠ Ban Automático",
        body: "Sozinho não bane. Precisa combo: unsigned + Temp + packer + horário + Prefetch + auth strings.\n\nEvita false ban. Fortalece true ban com dados.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Validação Binário",
        body: "Todo .exe suspeito no relatório com: nome, KB, SHA256, assinatura, caminho, DIE packer se tiver.\n\nEvidência documentada = veredito profissional.",
      },
    ],
    [
      "Anotar tamanho KB do .exe",
      "certutil -hashfile SHA256",
      "Verificar assinatura (Propriedades ou DIE)",
      "Registrar caminho completo",
      "DIE packer/entropia se disponível",
      "VT como apoio, não veredito único",
    ]),
  L("fluxo-completo", "Fluxo Completo — Do Zero ao Veredito", "analise",
    "Se você não sabe por onde começar, os caras te perguntam 50 coisas. Segue essa ordem SEMPRE e para de passar vergonha na SS.",
    [
      { kind: "intro", heading: "A ordem sagrada", body: "Telador amador pula etapa e toma exposed na call. Telador pro segue roteiro:\n\n1) Pin 171 ScreenS\n2) Prefetch + Temp + Recent\n3) Journal/USN se tiver\n4) Event Viewer / Sysmon\n5) DIE + SHA em .exe suspeito\n6) Veredito com print" },
      { kind: "modulo", heading: "📚 PASSO 1 — Scanner primeiro", body: "Gera pin, manda rodar o 171 ScreenS ANTES de fuçar manual.\n\nO scan já puxa serviços off, defender, strings, detecções. Usa isso como mapa — não ignora." },
      { kind: "modulo", heading: "📚 PASSO 2 — Artefatos Windows", body: "Prefetch (Win+R prefetch), Temp (%temp%), Recent (shell:recent).\n\nSão os 3 que o xiter mais esquece. 10 minutos aqui resolve 70% das SS básicas." },
      { kind: "modulo", heading: "📚 PASSO 3 — Logs e cruzamento", body: "Event Viewer (1102 = log limpo), Sysmon 8/10 se instalado.\n\nCruza horário: loader cmd/ps → abriu jogo → scan. Timeline é tua melhor amiga." },
      { kind: "modulo", heading: "📚 PASSO 4 — Validar binário", body: "Achou .exe? DIE + certutil -hashfile + assinatura.\n\nNão condena só por VT. Contexto + local + horário." },
      { kind: "veredito", heading: "📚 VEREDITO — Como decidir", body: "CLEAN = zero evidência concreta, só 'achismo'\nSUSPEITO = anti-forense, prefetch vazio, serviços off — sem cheat direto\nBAN = inject, auth+exec, delete mass + indicio, Event 8 no emulador\n\nRelatório: Resumo → Evidência 1, 2, 3 → Veredito. Print com data/hora em tudo.", example: "Mano, você tem 3 indícios médios + prefetch limpo + cmd 1 min antes do jogo. Não é 'talvez'. É suspeito forte. Next." },
    ], ["Pin scanner primeiro", "Prefetch → Temp → Recent", "Event/Sysmon se tiver", "DIE+SHA em suspeitos", "Classificar CLEAN/SUSPEITO/BAN", "Relatório com prints datados"]),
  // +20 DETECÇÕES
  L("det-auth-keyauth", "Detecção: Auth Online (KeyAuth)", "deteccoes",
    "Auth online deixa rastro em rede, Prefetch e strings. KeyAuth, LicenseAuth, painel custom — o loader telefona pra casa e o Windows anotou.",
    [
      {
        kind: "intro",
        heading: "O que é auth online?",
        body: "Loaders modernos validam key em servidor: KeyAuth, LicenseAuth, FluxAuth, painéis custom.\n\nDeixa URLs em Prefetch, tráfego em Uso de Dados, strings no 171 ScreenS.\n\nAuth confirmado + execução = BAN na maioria dos casos.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Onde Procurar",
        body: "171 ScreenS: strings licenseauth, keyauth, api.*.cloud\nUso de Dados: loader.exe com MB alto\nPrefetch: .pf do loader com hash de Temp/Downloads\nAppData: config.json com URL de auth",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Strings no Scan",
        body: "Scan puxa strings de processos e arquivos.\n\nURL de auth + .exe suspeito executado = combo letal.\n\nCruza com horário do ban.",
        example: "171 ScreenS achou licenseauth.cloud, loader.exe 12MB no Uso de Dados, Prefetch confirma execução. Auth confirmado, mano.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Timeline Auth → Jogo",
        body: "Loader autentica → injeta ou abre cheat → emulador.\n\nPrefetch loader às 21:29, jogo 21:30.\n\nNão aceita \"é VPN\" ou \"antivírus\".",
      },
      {
        kind: "zuera",
        heading: "💸 3. Painel Custom",
        body: "Nem todo auth é KeyAuth. Procura domínios .xyz, .ru, Discord webhook, IP direto.\n\nString suspeita + exec = documenta.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Auth Online",
        body: "Auth string + loader executado + tráfego = BAN.\n\nRelatório: URL encontrada, .exe, horário, print scan + Uso de Dados.",
      },
    ],
    [
      "Checar strings auth no 171 ScreenS",
      "Uso de Dados do loader",
      "Prefetch do mesmo .exe",
      "Timeline auth → abertura emulador",
      "Print scan + tráfego datado",
      "Veredito BAN se combo confirmado",
    ]),
  L("det-loader-temp", "Detecção: Loader no Temp", "deteccoes",
    "Loader baixado e executado de %TEMP% é padrão #1 do cheater brasileiro. Não tem desculpa — Temp não é pasta de programas.",
    [
      {
        kind: "intro",
        heading: "Por que Temp?",
        body: "Cheater baixa loader, executa de Temp achando que é \"temporário\" e apaga depois.\n\nPrefetch, Recent, BAM e journal guardam o rastro.\n\n.exe/.dll em Temp com data recente = olho aberto.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Varrer Temp",
        body: "Win+R → %temp% → ordena por Data modificação.\n\nProcura: .exe, .dll, .bat, nomes aleatórios (a8f2k.exe, svchost_update.exe).\n\nPasta criada hoje ou arquivo modificado minutos antes do jogo.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Padrão Clássico",
        body: "890KB unsigned, VMProtect no DIE, Prefetch confirma execução.\n\nMesmo deletado — Recent .lnk e BAM salvam.",
        example: "C:\\Temp\\svchost_update.exe — 890KB — VMProtect — Prefetch confirma. Svchost original não mora no Temp, campeão.",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. DIE + SHA Antes de Tudo",
        body: "Não executa. DIE + certutil -hashfile.\n\nDocumenta packer e hash no relatório.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Loader Temp",
        body: "Loader Temp + unsigned + packer + Prefetch = evidência forte.\n\nCombina com auth strings se tiver.",
      },
    ],
    [
      "Win+R %temp% ordenar por data",
      "Procurar .exe/.dll recentes",
      "DIE + SHA256 no achado",
      "Cruzar Prefetch e Recent",
      "Print caminho completo datado",
      "Veredito conforme combo",
    ]),
  L("det-prefetch-vazio", "Detecção: Prefetch Vazio", "deteccoes",
    "Prefetch com 2 arquivos num PC usado todo dia? Ou comprou ontem ou o xit rodou script de limpeza. Adivinha qual é mais comum.",
    [
      {
        kind: "intro",
        heading: "Regra de ouro",
        body: "PC Windows ativo acumula dezenas de .pf em horas.\n\nMenos de 5 .pf em máquina usada diariamente = SysMain off OU limpeza anti-forense.\n\nPrefetch vazio demais = suspeito, não inocente.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Contar .pf",
        body: "Win+R → prefetch → conta arquivos .pf.\n\nPergunta: usa PC todo dia? Há quanto tempo?\n\nCruza com SysMain status no 171 ScreenS.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. SysMain OFF",
        body: "SysMain desligado = Prefetch não gera novos .pf.\n\nBypass clássico. Pergunta na call — \"sempre foi assim\" = mentira.",
        example: "Prefetch: 2 arquivos. SysMain: OFF. Journal: 183 deletes ontem. Bypass genérico na cara.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Journal Confirma Limpeza",
        body: "Prefetch vazio + spike DELETE no USN = limpeza coordenada.\n\nTimeline no relatório.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Prefetch Vazio",
        body: "Sozinho = SUSPEITO mínimo.\nCom journal delete mass ou serviços off = SUSPEITO forte / BAN se combo.",
      },
    ],
    [
      "Contar arquivos .pf na Prefetch",
      "Verificar SysMain no 171 ScreenS",
      "Exportar journal — deletes em Prefetch?",
      "Perguntar uso diário do PC na call",
      "Print Prefetch + status SysMain",
      "Classificar SUSPEITO conforme combo",
    ]),
  L("det-defender-exclusao", "Detecção: Exclusão Defender", "deteccoes",
    "Pasta excluída do Defender com nome 'cheat' ou path em AppData random? O cara confessou sem querer.",
    [
      {
        kind: "intro",
        heading: "Exclusão = intenção",
        body: "Ninguém exclui pasta do scan por acidente.\n\nSegurança Windows → Gerenciar configurações → Exclusões.\n\nPasta Temp, AppData aleatório, ou nome explícito = red flag absoluta.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Listar Exclusões",
        body: "Na SS abre Segurança do Windows → Exclusões.\n\nPrint cada path excluído.\n\nVerifica se pasta ainda existe e o que tem dentro.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Nome que Entrega",
        body: "Exclusão: C:\\Users\\X\\AppData\\Local\\cheat\\\n\nNome da pasta já é veredito. Abre e varre conteúdo.",
        example: "Por que C:\\cheats tá excluído do Defender? Nome já entrega, mano. Abre a pasta.",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. Conteúdo da Pasta",
        body: "Se pasta existir: DIE + SHA em .exe/.dll.\n\nSe vazia: journal pode mostrar delete recente.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Exclusão Defender",
        body: "Exclusão pasta suspeita + conteúdo cheat = BAN.\nExclusão sem conteúdo = SUSPEITO forte.",
      },
    ],
    [
      "Abrir lista de exclusões Defender",
      "Print cada path excluído",
      "Verificar se pasta existe",
      "Varrer conteúdo — DIE + SHA",
      "Cruzar com Prefetch/journal",
      "Veredito conforme achado",
    ]),
  L("det-cmd-powershell", "Detecção: CMD/PowerShell", "deteccoes",
    "CMD ou PowerShell um minuto antes do jogo ou da SS? Loader script ou limpeza — coincidência não existe nessa profissão.",
    [
      {
        kind: "intro",
        heading: "Por que cmd/ps?",
        body: "Bypass via batch, PowerShell download cradle, script de limpeza.\n\nPrefetch: CMD.EXE-*.pf, POWERSHELL.EXE-*.pf com timestamp crítico.\n\nEvent 4104 se script block logging ativo.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Prefetch cmd/ps",
        body: "Win+R prefetch → procura CMD.EXE e POWERSHELL.EXE.\n\nOrdena por data. Compara com abertura do emulador e horário do scan.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Um Minuto Antes",
        body: "powershell.exe 14:26\nJournal: delete mass 14:27\nScan 14:35\n\nScript rodou, limpou, abriu telagem.",
        example: "PowerShell 14:26, delete mass 14:27, scan 14:35. Organização de arquivos ou script de bypass?",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Event 4104",
        body: "PowerShell Operational → script block.\n\nBase64, IEX, DownloadString = bypass clássico.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — CMD/PowerShell",
        body: "cmd/ps + delete mass ou loader Prefetch = SUSPEITO/BAN.\nContexto e horário no relatório.",
      },
    ],
    [
      "Prefetch CMD.EXE e POWERSHELL.EXE",
      "Comparar timestamp com jogo/scan",
      "Journal delete mass no mesmo horário?",
      "Event 4104 se disponível",
      "Print Prefetch cmd/ps datado",
      "Timeline no relatório",
    ]),
  L("det-bam", "Detecção: BAM (Background Activity)", "deteccoes",
    "Apagou Prefetch? BAM ainda registra última execução por usuário. Backup forense que o bypass burro esquece.",
    [
      {
        kind: "intro",
        heading: "O que é BAM?",
        body: "Background Activity Moderator — registry em HKLM\\SYSTEM\\CurrentControlSet\\Services\\bam\\State\\UserSettings.\n\nRegistra última execução de .exe por SID de usuário.\n\nPrefetch deletado? BAM pode salvar.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Exportar BAM",
        body: "Ferramentas parse BAM ou export manual do registry.\n\n171 ScreenS pode incluir. Cruza SID do user com entradas.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Loader no BAM, Prefetch Sumiu",
        body: "BAM mostra loader.exe 14:31.\nPrefetch foi deletado.\n\nBAM não mente.",
        example: "Prefetch limpo mas BAM mostra loader.exe 14:31. Apagou prova errada, campeão.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Timeline BAM",
        body: "Cruza timestamp BAM com ban, journal, Event Viewer.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — BAM",
        body: "Execução confirmada em BAM + .exe suspeito = evidência forte.\nPrint export datado.",
      },
    ],
    [
      "Exportar/parse BAM do user",
      "Procurar .exe suspeitos executados",
      "Cruzar com Prefetch (deletado?)",
      "Timeline BAM vs ban",
      "Print registry/export datado",
      "Incluir no relatório",
    ]),
  L("det-recent-lnk", "Detecção: Atalho Suspeito (Recent)", "deteccoes",
    "Deletou o .exe mas esqueceu o .lnk em Recent. Atalho aponta pro caminho real — obrigado pela prova.",
    [
      {
        kind: "intro",
        heading: "Recent não perdoa",
        body: "Win+R → shell:recent → atalhos de tudo que abriu.\n\nMesmo .exe deletado, .lnk pode apontar destino real.\n\nClica direito → Propriedades → Target.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Listar Recent",
        body: "Ordena por data. Procura .lnk de .exe, .dll suspeitos.\n\nTarget em Temp, Downloads, AppData random.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. .lnk Prova Abertura",
        body: ".lnk aponta C:\\Temp\\inject.dll — aberto 14:29.\n\nArquivo pode ter sido deletado — .lnk ficou.",
        example: "Recent mostra inject.dll aberto 14:29 de Temp. Deletou o arquivo mas esqueceu o atalho, genial.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Cruzar com Journal",
        body: "DELETE do .exe no USN + .lnk ainda em Recent = timeline completa.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Recent .lnk",
        body: ".lnk suspeito + target Temp/unsigned = evidência média-forte.\nPrint Propriedades com Target visível.",
      },
    ],
    [
      "Win+R shell:recent",
      "Ordenar por data",
      "Propriedades → Target do .lnk suspeito",
      "Cruzar data com Prefetch/journal",
      "Print Target datado",
      "SHA do destino se arquivo existir",
    ]),
  L("det-appdata-random", "Detecção: Pasta Aleatória AppData", "deteccoes",
    "Pasta AppData\\Local\\a8f2k9 com config.json? Cheater de auth deixa painel configurado igual deixa cueca na cadeira.",
    [
      {
        kind: "intro",
        heading: "AppData escondido",
        body: "Configs de cheat em pastas nome random: x7k2m, a8f2k9.\n\nArquivos .json, .cfg, .dll com URLs de auth.\n\nWin+R %appdata% e %localappdata%.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Varrer AppData",
        body: "Procura pastas com nome aleatório criadas recentemente.\n\nAbre .json/.cfg — URLs KeyAuth, keys, license.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. config.json Entrega",
        body: "Pasta x7k2m — config.json com keyauth URL e key parcial.",
        example: "Pasta a8f2k9 com config.json apontando licenseauth. Nome random + auth URL = ban material.",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. Strings + SHA",
        body: "171 ScreenS strings + SHA de .dll na pasta.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — AppData Random",
        body: "Pasta random + auth config = BAN.\nPrint pasta + conteúdo config.",
      },
    ],
    [
      "Win+R %appdata% e %localappdata%",
      "Pastas nome random recentes",
      "Abrir .json/.cfg — URLs auth",
      "Strings no 171 ScreenS",
      "SHA de .dll na pasta",
      "Print caminho completo",
    ]),
  L("det-servicos-off", "Detecção: Combo Serviços OFF", "deteccoes",
    "SysMain off, EventLog off, Defender off — trio desligado sem motivo? Bypass na cara dura.",
    [
      {
        kind: "intro",
        heading: "Tampering em combo",
        body: "Um serviço off pode ser acidente. Três críticos off juntos = bypass.\n\n171 ScreenS lista status. Pergunta na call.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Painel Serviços",
        body: "Scan 171 ScreenS → serviços.\n\nSysMain, EventLog, WinDefend, WSearch.\n\nAnota quais off e desde quando se souber.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Combo Clássico",
        body: "3+ serviços off — user não explica.\n\nCorrelaciona Prefetch vazio, logs limpos.",
        example: "SysMain, EventLog, Defender off. Tu desligou metade do Windows ou o PC veio quebrado?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Serviços OFF",
        body: "Combo off + anti-forense = SUSPEITO forte.\nPrint painel scan.",
      },
    ],
    [
      "Checar serviços no 171 ScreenS",
      "Contar quantos críticos off",
      "Perguntar motivo na call",
      "Correlacionar Prefetch/journal",
      "Print status serviços",
      "Classificar SUSPEITO/BAN combo",
    ]),
  L("det-usn-delete-mass", "Detecção: Spike DELETE Journal", "deteccoes",
    "183 deletes em 2 minutos na Prefetch? Isso não é organização — é limpeza coordenada antes da SS.",
    [
      {
        kind: "intro",
        heading: "Threshold de delete",
        body: "50+ deletes em 5 min em Prefetch/Temp/Logs = limpeza.\n\nUSN Journal export — conta DELETE por minuto.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Contar Deletes",
        body: "Export USN período 24-48h.\n\nFiltra DELETE. Agrupa por minuto.\n\nSpike antes do scan = modo pânico.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Spike Clássico",
        body: "14:28-14:29 — 183 deletes — maioria Prefetch.\nScan 14:35.",
        example: "183 deletes em 2 min na Prefetch. Tu tava limpando prova ou organizando foto de família?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Delete Mass",
        body: "Spike + horário antes scan = SUSPEITO/BAN anti-forense.\nTimeline no relatório.",
      },
    ],
    [
      "Export USN do período",
      "Filtrar e contar DELETE",
      "Identificar spike por minuto",
      "Timeline delete → scan",
      "Print export/gráfico",
      "Documentar no relatório",
    ]),
  L("det-recycle-bin", "Detecção: Lixeira Esvaziada", "deteccoes",
    "Esvaziou lixeira no horário do ban? Clássico esconder .exe deletado. Journal e pergunta na call fecham o ciclo.",
    [
      {
        kind: "intro",
        heading: "Lixeira na telagem",
        body: "$Recycle.Bin guarda deletes até esvaziar.\n\nUser esvazia lixeira minutos antes da SS = anti-forense.\n\nJournal mostra purge. Pergunta direto na call.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Como Verificar",
        body: "Pergunta: esvaziou lixeira recentemente?\n\nJournal USN — eventos em $Recycle.Bin.\n\nHesitação ou \"sim, agora há pouco\" + horário ban = suspeito.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Timeline Lixeira",
        body: "User esvaziou 14:27 — journal confirma purge.\nScan 14:35.",
        example: "Esvaziou lixeira 14:27, scan 14:35. Deletou loader e esvaziou achando que sumiu?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Lixeira",
        body: "Esvaziar no horário crítico = indício médio.\nCombo com delete mass = SUSPEITO forte.",
      },
    ],
    [
      "Perguntar sobre lixeira na call",
      "Journal — purge $Recycle.Bin",
      "Cruzar horário com ban/scan",
      "Anotar resposta do user",
      "Timeline no relatório",
      "Combinar com outros indícios",
    ]),
  L("det-downloads-desktop", "Detecção: Loader Downloads/Desktop", "deteccoes",
    "Loader no Desktop ou Downloads com nome Client.exe — cheater preguiçoso que nem esconde direito.",
    [
      {
        kind: "intro",
        heading: "Locais óbvios",
        body: "Downloads\\setup.exe, Desktop\\update.exe, Client.exe — nomes genéricos.\n\nCriado hoje, unsigned, DIE mostra packer.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Varrer Locais",
        body: "Explorer → Downloads e Desktop.\n\nOrdena por data. Win+R userprofile\\Downloads.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Client.exe Clássico",
        body: "Desktop\\Client.exe — 1.2MB — criado hoje — VMProtect.",
        example: "Client.exe 1.2MB no Desktop criado hoje. Client de quê? Cheat ou cliente de pizzaria?",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. DIE + Prefetch",
        body: "DIE + SHA + Prefetch confirma execução.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Downloads/Desktop",
        body: "Loader visível + packer + Prefetch = evidência forte.",
      },
    ],
    [
      "Varrer Downloads e Desktop",
      "Ordenar por data modificação",
      "DIE + SHA em .exe suspeito",
      "Cruzar Prefetch",
      "Print caminho datado",
      "Veredito conforme combo",
    ]),
  L("det-scheduled-task", "Detecção: Tarefa Agendada", "deteccoes",
    "Cheat que persiste via Task Scheduler — nome WindowsUpdate apontando loader no Temp. Criatividade de bypass nível infantil.",
    [
      {
        kind: "intro",
        heading: "Persistência via Task",
        body: "taskschd.msc — tarefas agendadas.\n\nAção apontando .exe em Temp ou script PowerShell.\n\nNome disfarçado: WindowsUpdate, SystemCheck.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Task Scheduler",
        body: "Win+R taskschd.msc → Task Scheduler Library.\n\nOlha Ação, Autor, última execução.\n\nPrint tarefa suspeita completa.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Nome Falso",
        body: "Task 'WindowsUpdate' → C:\\Temp\\loader.exe\n\nMicrosoft não agenda update apontando Temp.",
        example: "Tarefa WindowsUpdate rodando loader.exe do Temp. Update da Microsoft mudou de endereço?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Scheduled Task",
        body: "Task apontando loader = BAN material.\nPrint ação + caminho + autor.",
      },
    ],
    [
      "Win+R taskschd.msc",
      "Listar tarefas — ação suspeita?",
      "Verificar caminho do .exe na ação",
      "DIE + SHA do executável",
      "Print tarefa completa",
      "Cruzar Prefetch/última execução",
    ]),
  L("det-run-registry", "Detecção: Run/RunOnce", "deteccoes",
    "Persistência em Run keys — svchost apontando .exe no AppData. Registry não mente.",
    [
      {
        kind: "intro",
        heading: "Run keys",
        body: "HKCU/HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run e RunOnce.\n\nValores apontando loader disfarçado.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Regedit Run",
        body: "Win+R regedit → navega Run keys.\n\nAnota valores suspeitos. Verifica se arquivo existe.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. svchost Falso",
        body: "Run: svchost → C:\\Users\\X\\AppData\\Local\\tmp\\svc.exe\n\nSvchost real não mora em AppData.",
        example: "Run key aponta svc.exe no AppData disfarçado de svchost. Svchost da Microsoft mudou de casa?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Run Registry",
        body: "Run apontando loader = persistência documentada.\nSHA + Prefetch se executou.",
      },
    ],
    [
      "regedit → Run e RunOnce keys",
      "Valores apontando .exe suspeito",
      "Arquivo no caminho existe?",
      "DIE + SHA256",
      "Print registry datado",
      "Prefetch do executável",
    ]),
  L("det-dll-sem-assinatura", "Detecção: DLL Sem Assinatura", "deteccoes",
    "DLL unsigned em Temp carregada no emulador — material de inject. System Informer confirma na hora.",
    [
      {
        kind: "intro",
        heading: "DLL suspeita",
        body: "Propriedades → Assinaturas Digitais vazias.\nTemp + unsigned + emulador com DLL carregada = inject.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Validar DLL",
        body: "Acha .dll → Propriedades assinatura.\nSystem Informer → HD-Player → Modules.\n\nConfirma se DLL está carregada no processo.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. inject.dll no Emulador",
        body: "inject.dll — unsigned — 892KB — Temp.\nSystem Informer confirma no HD-Player.",
        example: "inject.dll unsigned no Temp carregada no emulador. Inject de vacina ou de cheat?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — DLL Unsigned",
        body: "DLL unsigned Temp no emulador = BAN competitive.\nPrint SI Modules + SHA256.",
      },
    ],
    [
      "Localizar .dll suspeita",
      "Verificar assinatura Authenticode",
      "System Informer → Modules emulador",
      "certutil -hashfile SHA256",
      "Print módulo carregado",
      "Veredito BAN se confirmado",
    ]),
  L("det-hosts-modificado", "Detecção: Hosts Modificado", "deteccoes",
    "hosts file redirecionando update.microsoft.com pro localhost? Bloqueio de AV update clássico de cheater.",
    [
      {
        kind: "intro",
        heading: "Arquivo hosts",
        body: "C:\\Windows\\System32\\drivers\\etc\\hosts\n\nEntradas não padrão — bloqueio update, redirect auth.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Abrir hosts",
        body: "Notepad como admin → abre hosts.\n\nCompara com padrão (só localhost comentado).\n\nData modificação recente?",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Bloqueio Update",
        body: "127.0.0.1 update.microsoft.com\n\nBloqueio de Windows Update / Defender update.",
        example: "hosts bloqueia update.microsoft.com. Tu bloqueou update ou o Windows se auto-sabota?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Hosts",
        body: "Hosts modificado + outras evidências = SUSPEITO/BAN.\nPrint arquivo + data modificação.",
      },
    ],
    [
      "Abrir hosts como admin",
      "Comparar com padrão Windows",
      "Entradas estranhas anotadas",
      "Data modificação do arquivo",
      "Print hosts datado",
      "Cruzar com bypass combo",
    ]),
  L("det-amcache", "Detecção: Amcache/Shimcache", "deteccoes",
    "Prefetch sumiu? Amcache ainda registra execução — path, SHA, compile time. Backup que bypass burro ignora.",
    [
      {
        kind: "intro",
        heading: "Amcache forense",
        body: "Amcache/Shimcache registra programas executados.\n\nFerramentas parse Amcache. Path, SHA, compile time.\n\nBackup quando Prefetch deletado.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Parse Amcache",
        body: "Export/parse com ferramenta forense ou área do scan.\n\nProcura loader.exe no período do ban.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Prefetch Deletado, Amcache Salva",
        body: "Amcache: loader.exe 14:30 — Prefetch deletado.",
        example: "Prefetch limpo mas Amcache mostra loader 14:30. Apagou a prova errada de novo.",
      },
      {
        kind: "tecnica",
        heading: "🕒 2. Cruzar BAM + SHA",
        body: "Amcache SHA + BAM timestamp + journal = timeline sólida.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Amcache",
        body: "Execução confirmada Amcache + .exe suspeito = evidência forte.",
      },
    ],
    [
      "Parse/export Amcache",
      "Procurar .exe suspeitos no período",
      "Cruzar com BAM e Prefetch",
      "SHA do binário no Amcache",
      "Timeline execução",
      "Print export datado",
    ]),
  L("det-browser-download", "Detecção: Download pelo Browser", "deteccoes",
    "Histórico do Chrome mostra download de cheat-loader.zip do Discord CDN. O browser dedurou antes da Prefetch.",
    [
      {
        kind: "intro",
        heading: "Browser history",
        body: "Chrome History, Edge Downloads.\n\nURL de site cheat, Discord CDN, MediaFire.\n\nCruza com Downloads folder e Prefetch.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Histórico Downloads",
        body: "Chrome: ctrl+H → Downloads.\nEdge: Ctrl+J.\n\nAnota URL e horário. Abre pasta Downloads.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Discord CDN",
        body: "Download: cheat-loader.zip de discord CDN 14:00.\nPrefetch loader 14:05.",
        example: "Baixou cheat-loader.zip do Discord 14:00. Discord virou loja de cheat agora?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Browser Download",
        body: "URL cheat + .exe executado = evidência forte.\nPrint histórico + Prefetch.",
      },
    ],
    [
      "Histórico downloads Chrome/Edge",
      "Anotar URL e horário",
      "Cruzar pasta Downloads",
      "Prefetch do .exe baixado",
      "Print histórico datado",
      "Timeline download → exec",
    ]),
  L("det-srum", "Detecção: SRUM (Network)", "deteccoes",
    "SRUM registra tráfego por app com timestamp cirúrgico. unknown.exe 45MB 14:25-14:40 — Uso de Dados on steroids.",
    [
      {
        kind: "intro",
        heading: "System Resource Usage Monitor",
        body: "SRUM em registry — tráfego rede por aplicativo com horário preciso.\n\nForense avançada. Parse com ferramentas.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Parse SRUM",
        body: "Export SRUM do período.\n\nProcura apps desconhecidos com MB alto no horário do ban.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. unknown.exe no SRUM",
        body: "SRUM: unknown.exe 45MB 14:25-14:40.\nCruza Uso de Dados e Prefetch.",
        example: "SRUM mostra unknown.exe 45MB na hora do ban. App fantasma com tráfego de auth?",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — SRUM",
        body: "App desconhecido + tráfego alto + horário = evidência média-forte.\nCombina com scan strings.",
      },
    ],
    [
      "Parse/export SRUM",
      "App desconhecido com tráfego alto",
      "Horário vs ban/emulador",
      "Cruzar Uso de Dados e scan",
      "Prefetch do mesmo .exe",
      "Timeline no relatório",
    ]),
  L("det-veredito-basico", "Detecção: Montar Veredito", "deteccoes",
    "CLEAN, SUSPEITO ou BAN — sem passar vergonha na call. Regras claras pra telador que não quer tomar exposed.",
    [
      {
        kind: "intro",
        heading: "Veredito profissional",
        body: "Telador amador: \"acho que é xit\". Telador pro: evidência numerada + classificação + prints datados.\n\nRegras evitam ban injusto e fortalecem ban justo.",
      },
      {
        kind: "modulo",
        heading: "📚 MÓDULO 1 — Três Vereditos",
        body: "CLEAN = zero evidência concreta, só achismo.\nSUSPEITO = indícios médios, anti-forense, prefetch vazio — sem cheat direto.\nBAN = prova: inject Event 8, auth+exec, delete mass + indicio, DLL unsigned no emulador.",
      },
      {
        kind: "tecnica",
        heading: "🕵️ 1. Regra de Contagem",
        body: "1 evidência FORTE = BAN (Event 8 emulador, auth confirmado+exec, inject DLL confirmada).\n3+ evidências MÉDIAS = BAN (prefetch vazio + cmd + delete mass).\nSó prefetch vazio = SUSPEITO mínimo.",
        example: "1 forte OU 3 médias = BAN. Só 'tô com raiva' = CLEAN. Simples assim.",
      },
      {
        kind: "tecnica",
        heading: "🛠️ 2. Formato Relatório",
        body: "Resumo 2 linhas → Evidência 1, 2, 3 com print → Veredito final.\n\nTodo print com data/hora visível.\n\nFrase na call: evidência + horário + artefato.",
      },
      {
        kind: "zuera",
        heading: "❌ 3. Erros que Expõem",
        body: "Ban só por VT. Ban só por \"parece suspeito\". Não documentar horário.\n\nUser pede \"mostra prova\" e telador gagueja = exposed.",
      },
      {
        kind: "veredito",
        heading: "📚 VEREDITO — Fechamento",
        body: "Lista evidências → classifica força → veredito claro → prints datados.\n\nStatus: Graduado. Pode puxar próxima SS sem passar vergonha.",
        example: "Mano, 3 indícios médios + prefetch limpo + cmd 1 min antes do jogo. Não é 'talvez'. Suspeito forte. Next.",
      },
    ],
    [
      "Listar todas evidências encontradas",
      "Classificar força (forte/média/fraca)",
      "Aplicar regra 1 forte ou 3 médias",
      "Veredito CLEAN/SUSPEITO/BAN claro",
      "Relatório: resumo + evidências + prints",
      "Frase objetiva na call com horário",
    ]),
];
