import type { Lesson } from "./types";

const L = (
  order: number,
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ order, id, title, categoryId, tier: "tier3", intro, sections, checklist });

export const tier3Extra: Lesson[] = [
  L(16, "dma-fuser", "DMA — Fuser & HDMI Splitter", "privado",
    "Hardware cheat esconde input/output — fuser combina sinais.",
    [{ heading: "O que é", body: "Placa entre GPU e monitor + segundo PC lendo memória. Sem processo no PC alvo.", example: "Scan alvo: 100% clean\nMesa: segunda torre + fuser HDMI\n→ Investigar hardware" }],
    ["Perguntar setup", "Scan DMA area", "Câmera mesa", "Regra servidor"]),
  L(17, "reflective-dll", "Reflective DLL Injection", "privado",
    "DLL carregada da memória sem arquivo no disco.",
    [{ heading: "Sinais", body: "Event 8 sem Event 11 prévio. DLL em memória sem path no disco.", example: "Event 8 HD-Player\nSem arquivo inject.dll no journal\nDump: DLL em memória" }],
    ["Event 8 sem file", "Dump memória", "SI modules", "Veredito"]),
  L(18, "manual-map-deep", "Manual Map — Detecção Profunda", "privado",
    "Manual mapping não aparece em LoadLibrary clássico.",
    [{ heading: "Hunt", body: "Event 10 + memória com PE header anômalo. Strings no dump.", example: "Manual map: sem Event 7 ImageLoaded\nMas Event 8 presente" }],
    ["Dump análise", "Event 8/10", "PE em memória", "Relatório"]),
  L(19, "ipv6-tunnel", "Túnel IPv6 & Localhost Relay", "privado",
    "Remote bypass via localhost e túneis IPv6.",
    [{ heading: "Event 3", body: "127.0.0.1, ::1, fe80:: — relay entre processos locais.", example: "anydesk → 127.0.0.1:5959\nProcesso B escuta mesma porta" }],
    ["Event 3 localhost", "netstat", "Processos listening", "Correlacionar"]),
  L(20, "atom-bombing", "Atom Bombing & Técnicas Exóticas", "privado",
    "Injeção via global atoms — raro mas existe em cheats privados.",
    [{ heading: "Conceito", body: "GlobalAddAtom + QueueUserAPC — sem arquivo. Memória e Event 8 anômalo.", example: "Sem .exe no disco\nEvent 8 start address fora de módulo conhecido" }],
    ["Dump memória", "Event 8 address", "SI threads", "Escalar"]),
  L(21, "kernel-callbacks", "Kernel Callbacks & Rootkit", "privado",
    "Rootkit altera callbacks do kernel — Sysmon pode ser cego.",
    [{ heading: "Sinais", body: "Sysmon parado, drivers ocultos, gap total em logs mas gameplay cheat.", example: "Sysmon OFF + driver unsigned + scan clean\n→ Kernel level" }],
    ["Drivers", "Sysmon status", "Offline image", "Especialista"]),
  L(22, "pin-review-samuca", "Review de Pin — Método Samuca", "privado",
    "Como Samuca revisa pins no grupo privado — ordem de análise.",
    [{ heading: "Ordem", body: "1 Scan completo 2 Timeline 3 Memória se necessário 4 Hardware se DMA 5 Veredito", example: "Pin enviado incompleto → pedir prefetch antes de opinar" }],
    ["Scan primeiro", "Não apressar BAN", "Pedir evidência faltante", "Formato padrão"]),
  L(23, "ban-appeal-analise", "Análise de Appeal — Defender Ban", "privado",
    "Quando user apela — re-analisar sem viés.",
    [{ heading: "Processo", body: "Reler timeline, pedir novos artefatos, comparar com relatório original.", example: "Appeal: 'prefetch era do jogo'\n→ Verificar hash e path do .pf" }],
    ["Relatório original", "Novos artefatos", "Comparar SHA", "Veredito final"]),
  L(24, "enterprise-strings", "Enterprise Strings — Caça Custom", "privado",
    "Usar patterns enterprise do 171 ScreenS pra cheat privado.",
    [{ heading: "Setup", body: "Patterns XOR, auth custom, nomes de cheat da operação.", example: "Pattern 'solvynx' pegou loader não listado publicamente" }],
    ["Patterns atualizados", "Rescan", "Validar FP", "Documentar hit"]),
  L(25, "operacao-telagem", "Operação de Telagem em Escala", "privado",
    "Como montar time de teladores com padrão único.",
    [{ heading: "Padrão", body: "Checklist único, template relatório, tier de escalação (I → II → III).", example: "Telador I faz básico\nDúvida → II\nDMA → III + Samuca" }],
    ["Checklist time", "Template único", "Escalonamento", "QA semanal"]),
];
