import type { Lesson } from "./types";

const L = (
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ id, title, categoryId, tier: "tier1", intro, sections, checklist });

export const tier1Lessons: Lesson[] = [
  L("prefetch", "Prefetch — Guia Completo", "windows",
    "Prefetch (.pf) é o artefato #1 do telador. Cheat apagado do disco ainda deixa rastro em C:\\Windows\\Prefetch.",
    [
      { heading: "Localização e formato", body: "C:\\Windows\\Prefetch\\ — cada execução gera NOME.EXE-HASH.pf. O hash muda se o caminho mudar. WinPrefetchView (NirSoft) mostra última execução, runs e arquivos acessados.", example: "LOADER.EXE-F8A2B1C0.pf\nÚltima execução: 09/06/2026 14:32\nRuns: 3\nUsuário: \"nunca usei cheat\"\n→ Execução 2 min antes do scan = SUSPEITO." },
      { heading: "O que procurar", body: "Loaders em Temp/AppData, cmd.exe e powershell.exe rodando perto do ban, cleaners (CCleaner, BleachBit), e .pf de .exe com nome aleatório (a8f2k.exe)." },
      { heading: "Prefetch limpo = bypass", body: "Pasta vazia ou 2-3 arquivos em PC usado todo dia = SysMain OFF ou limpeza manual. Isso JÁ é anti-forense — não precisa achar o cheat." },
      { heading: "Cruzamento", body: "Prefetch + Journal + 171 ScreenS. Se scan acusa auth e .pf do loader bate no horário, veredito fica sólido." },
    ], ["Listar .pf dos últimos 7 dias", "Marcar execuções perto do ban", "Verificar se pasta está vazia demais", "Cruzar com detecções do scanner"]),
  L("temp-recent", "Temp · Recent · AppData", "windows",
    "99% dos cheaters esquecem arquivo em Temp ou atalho em Recent. Telador que só olha Prefetch perde metade.",
    [
      { heading: "%TEMP%", body: "Win+R → %temp%. Ordene por Data. Loaders, .dll inject, .bat de limpeza ficam aqui.", example: "C:\\Users\\X\\AppData\\Local\\Temp\\inject.dll\n892 KB — modificado 14:30\n→ DIE + SHA256 + VirusTotal" },
      { heading: "Recent (.lnk)", body: "AppData\\Roaming\\Microsoft\\Windows\\Recent\\. Atalhos de arquivos abertos — mostra .exe aberto mesmo após delete." },
      { heading: "AppData", body: "Local/Roaming com pastas de nome aleatório, configs de auth, tokens JSON." },
      { heading: "Downloads e Desktop", body: "Loaders baixados pelo browser. Nome tipo 'setup.exe', 'update.exe' em Desktop = red flag." },
    ], ["Varrer %TEMP% por .exe/.dll", "Checar Recent por .lnk", "AppData pastas aleatórias", "Downloads + Desktop"]),
  L("uso-dados", "Uso de Dados", "windows",
    "Windows registra consumo de internet por app. Auth online e phone-home aparecem aqui.",
    [
      { heading: "Onde abrir", body: "Configurações → Rede e Internet → Uso de dados. Últimos 30 dias por aplicativo." },
      { heading: "Red flags", body: "Apps desconhecidos com tráfego alto, .exe em Temp consumindo MB, nomes genéricos (Host, Service).", example: "Loader_v2.exe — 45 MB em 7 dias\nRuntimeBroker_fake — tráfego constante\n→ Cruzar com prefetch do mesmo .exe" },
      { heading: "Internal vs loader", body: "Cheat internal raramente consome muito. Loader/auth sim — foco em .exe suspeito com tráfego." },
    ], ["Filtrar últimos 7 dias", "Anotar apps desconhecidos", "Cruzar horário com scan", "Print com data"]),
  L("antivirus", "Antivírus & Defender", "windows",
    "Histórico e exclusões do Defender são evidência direta. Exclusão de pasta = clássico de cheater.",
    [
      { heading: "Histórico", body: "Segurança do Windows → Proteção → Histórico de proteção.", example: "Trojan:Win32/CheatGen — Quarentenado — Usuário RESTAUROU\n→ Ban justificado." },
      { heading: "Exclusões", body: "Gerenciar configurações → Exclusões. Pasta C:\\cheats excluída = red flag absoluta." },
      { heading: "Tampering", body: "Defender OFF, serviço parado, proteção em tempo real desativada — painel 171 ScreenS lista isso." },
    ], ["Histórico de proteção", "Lista de exclusões", "Defender ativo?", "Print detecções restauradas"]),
  L("journal-trace", "Journal Trace (USN)", "bypass",
    "USN Journal registra create, delete, rename no NTFS. Quem limpou prefetch/temp deixa rastro.",
    [
      { heading: "O que é", body: "Update Sequence Number — log do sistema de arquivos. MFTECmd, JournalTrace ou área do 171 ScreenS." },
      { heading: "Delete em massa", body: "Centenas de DELETE em Prefetch/Temp/Logs em minutos = limpeza.", example: "14:28 DELETE prefetch\\LOADER*.pf\n14:28 DELETE 47 arquivos Temp\n14:30 Scan iniciado\n→ Limpou antes da telagem." },
      { heading: "Rename trick", body: "cheat.exe renomeado para notepad.exe — journal mostra RENAME." },
    ], ["Exportar journal do período", "Filtrar DELETE em massa", "Procurar RENAME", "Timeline delete → scan"]),
  L("delete-mass", "Delete & Limpeza", "bypass",
    "Bypass genérico quase sempre deleta algo. Separar limpeza manual de comportamento normal.",
    [
      { heading: "Sinais", body: "Prefetch vazio, Temp limpo, Event log sem entradas recentes, USN com spike DELETE, lixeira esvaziada no horário crítico." },
      { heading: "Cleaners", body: "CCleaner, BleachBit, privaZer — .pf deles + journal de deletes = anti-forense.", example: "CCleaner 14:25 → 200 deletes → Scan CLEAN mas bypass evidente\n→ SUSPEITO/BAN anti-forense" },
    ], ["Integridade Prefetch/Temp", ".pf de cleaners", "Horário delete vs scan", "Documentar no relatório"]),
  L("bypass-lento", "Lentidão de Bypass", "bypass",
    "Bypass mal feito deixa PC lento, serviços off e emulador travando.",
    [
      { heading: "Sinais", body: "Boot 2-3x mais lento, emulador demora, explorer CPU alta, drivers kernel não assinados." },
      { heading: "Serviços OFF", body: "SysMain, PcaSvc, EventLog, WSearch desligados sem motivo.", example: "Scan: SysMain OFF, EventLog OFF, Defender OFF\nUser: \"sempre foi assim\"\n→ Improvável. Tampering." },
    ], ["Serviços no painel scan", "Perguntar sobre lentidão", "Drivers no System Informer", "Correlacionar"]),
  L("system-informer-intro", "System Informer — Intro", "ferramentas",
    "Monitor moderno de processos. Ver DLLs, handles, threads e rede ao vivo.",
    [
      { heading: "Setup", body: "systeminformer.sourceforge.io — rode como admin. Abas: Processes, Services, Network." },
      { heading: "DLLs", body: "Processo do emulador → Modules. DLL sem assinatura em C:\\Temp = inject.", example: "HD-Player.exe:\nunknown.dll C:\\Temp\\ — SEM ASSINATURA\n→ Print + SHA" },
    ], ["Admin", "Filtrar emulador", "DLLs não assinadas", "Print Network se estranho"]),
  L("die", "DIE — Detect It Easy", "ferramentas",
    "Antes de rodar .exe suspeito, passe no DIE. Packer e entropia revelam cheat.",
    [
      { heading: "Scan", body: "Arraste .exe. Mostra packer (UPX, VMProtect, Themida), .NET vs Native, entropia.", example: "update.exe — VMProtect 3.x — Entropia 7.8 — Sem assinatura\n→ Não é update legítimo." },
      { heading: "SHA256", body: "certutil -hashfile arquivo SHA256. VT como referência, não veredito único." },
    ], ["DIE em .exe suspeito", "Anotar packer", "SHA256", "VT como apoio"]),
  L("event-viewer", "Event Viewer", "ferramentas",
    "Logs nativos. Event 1102 = Security log limpo — banível em competitive.",
    [
      { heading: "Logs", body: "eventvwr.msc → Security, System, Application. Filtre horário do ban." },
      { heading: "IDs importantes", body: "1102 log cleared, 4624/4625 logon, 4688 processo criado, PowerShell Operational.", example: "Event 1102 — 14:27 — Administrator\n→ Log limpo 8 min antes do scan." },
    ], ["Event Viewer aberto", "Filtrar Security", "Procurar 1102", "Print datado"]),
  L("sysmon-event-5", "Sysmon Event 5 — Process Terminated", "sysmon",
    "Registra quando processo termina. Ver o que fechou antes do scan.",
    [
      { heading: "Campos", body: "ProcessGuid, Image, User. Sysmon → Operational." },
      { heading: "Caso", body: "Loader fechado segundos antes do AnyDesk.", example: "Event 5: loader.exe terminated 14:34:02\nScan 14:34:30\n→ Fechou na correria." },
    ], ["Sysmon instalado?", "Filtrar Event 5", "Cruzar Image com Prefetch", "Documentar gap"]),
  L("sysmon-event-8", "Sysmon Event 8 — CreateRemoteThread", "sysmon",
    "Thread remota = injeção DLL / manual map. Um dos melhores indicadores.",
    [
      { heading: "Campos", body: "SourceImage, TargetImage, StartAddress.", example: "Source: injector.exe → Target: HD-Player.exe\n→ Injeção no emulador." },
      { heading: "FP", body: "AV/debugger geram Event 8. Contexto: injector desconhecido + emulador = ban." },
    ], ["Filtrar Event 8", "Source suspeito?", "Target = emulador?", "Print completo"]),
  L("sysmon-event-10", "Sysmon Event 10 — Process Access", "sysmon",
    "OpenProcess — cheat external lê memória do emulador.",
    [
      { heading: "GrantedAccess", body: "0x1F0FFF = ALL_ACCESS. Cheat external pede acesso alto.", example: "cheat.exe → HD-Player.exe — 0x1F0FFF\n→ External memory read." },
    ], ["Filtrar Event 10", "Access alto no emulador", "Cruzar Source com Prefetch", "Hash do Source"]),
  L("exe-suspeito", ".exe Suspeito — KB, SHA, Assinatura", "analise",
    "Validar binário com dados concretos. Evita ban injusto e fortalece ban justo.",
    [
      { heading: "Tamanho", body: "Loaders têm tamanho típico. Compare com builds conhecidos." },
      { heading: "SHA256", body: "certutil -hashfile. Hash único no relatório.", example: "loader.exe — 1204 KB — SHA a3f2... — Não assinado — VT 2/72" },
      { heading: "Assinatura", body: "Unsigned + Temp = red flag. Não ban automático sem contexto." },
    ], ["Tamanho KB", "SHA256", "Assinatura", "VT como apoio"]),
  L("fluxo-completo", "Fluxo Completo — Iniciante ao Veredito", "analise",
    "Ordem certa separa telador amador de pro. Segue isso.",
    [
      { heading: "Ordem", body: "1) 171 ScreenS 2) Prefetch+Journal+Temp 3) Sysmon/Event 4) DIE+SHA 5) System Informer 6) Veredito", example: "CLEAN = zero evidência\nSUSPEITO = anti-forense sem prova final\nBAN = inject, auth, delete+prefetch" },
      { heading: "Relatório", body: "Resumo → Evidências numeradas → Veredito. Prints datados." },
    ], ["Scan primeiro", "Artefatos na ordem", "DIE/SHA", "Veredito + prints"]),
  // +20 DETECÇÕES
  L("det-auth-keyauth", "Detecção: Auth Online (KeyAuth)", "deteccoes", "Auth servers deixam rastro em rede, prefetch e strings.", [{ heading: "Onde", body: "KeyAuth, LicenseAuth, custom panels — URLs em prefetch, uso de dados, strings no scan.", example: "171 ScreenS: licenseauth.cloud\nUso de dados: loader.exe 12MB\n→ Auth confirmado." }], ["Auth no scan", "Uso de dados", "Prefetch do loader", "Timeline"]),
  L("det-loader-temp", "Detecção: Loader no Temp", "deteccoes", "Loader baixado e executado de %TEMP% é padrão #1.", [{ heading: "Padrão", body: ".exe/.dll em Temp com data recente, sem assinatura, DIE mostra packer.", example: "C:\\Temp\\svchost_update.exe — 890KB — VMProtect" }], ["Varrer Temp", "DIE", "SHA", "Prefetch"]),
  L("det-prefetch-vazio", "Detecção: Prefetch Vazio", "deteccoes", "Pasta Prefetch vazia em PC ativo = anti-forense.", [{ heading: "Regra", body: "Menos de 5 .pf em PC usado diariamente = SysMain off ou limpeza.", example: "Prefetch: 2 arquivos\nSysMain: OFF\n→ Bypass genérico." }], ["Contar .pf", "SysMain status", "Journal deletes", "Relatório"]),
  L("det-defender-exclusao", "Detecção: Exclusão Defender", "deteccoes", "Pasta excluída da proteção = cheat instalado ali.", [{ heading: "Como", body: "Segurança → Exclusões. Pasta com nome de cheat, Temp, ou AppData aleatório.", example: "Exclusão: C:\\Users\\X\\AppData\\Local\\cheat\\" }], ["Lista exclusões", "Print", "Conteúdo da pasta", "Veredito"]),
  L("det-cmd-powershell", "Detecção: CMD/PowerShell", "deteccoes", "cmd/powershell antes do scan = loader ou limpeza.", [{ heading: "Prefetch", body: "CMD.EXE-*.pf e POWERSHELL.EXE-*.pf com timestamp perto do ban.", example: "powershell.exe 14:26\nJournal: delete mass 14:27\nScan 14:35" }], ["Prefetch cmd/ps", "Journal", "Event 4104 se tiver", "Contexto"]),
  L("det-bam", "Detecção: BAM (Background Activity)", "deteccoes", "BAM registra execução mesmo sem prefetch.", [{ heading: "Registry", body: "HKLM\\SYSTEM\\CurrentControlSet\\Services\\bam\\State\\UserSettings — última execução por SID.", example: "BAM mostra loader.exe 14:31 — prefetch foi deletado\n→ BAM salva." }], ["Exportar BAM", "Cruzar SID", "Timeline", "Print"]),
  L("det-recent-lnk", "Detecção: Atalho Suspeito (Recent)", "deteccoes", ".lnk em Recent prova que arquivo foi aberto.", [{ heading: "Uso", body: "Recent mostra .exe aberto mesmo deletado depois.", example: ".lnk aponta para C:\\Temp\\inject.dll — aberto 14:29" }], ["Listar Recent", "Target do .lnk", "Data", "Print"]),
  L("det-appdata-random", "Detecção: Pasta Aleatória AppData", "deteccoes", "Configs de cheat em pastas com nome random.", [{ heading: "Padrão", body: "AppData\\Local\\a8f2k9\\ ou similar com .json, .cfg, .dll.", example: "Pasta x7k2m — config.json com keyauth URL" }], ["Varrer AppData", "Arquivos .json/.cfg", "Strings", "SHA"]),
  L("det-servicos-off", "Detecção: Combo Serviços OFF", "deteccoes", "Múltiplos serviços críticos off = tampering.", [{ heading: "Combo", body: "SysMain + EventLog + Defender off juntos = bypass.", example: "3 serviços OFF no 171 ScreenS — user não explica" }], ["Painel serviços", "Perguntar motivo", "Journal", "Veredito"]),
  L("det-usn-delete-mass", "Detecção: Spike DELETE Journal", "deteccoes", "Pico de deletes em minutos = limpeza coordenada.", [{ heading: "Threshold", body: "50+ deletes em 5 min em Prefetch/Temp/Logs.", example: "14:28-14:29 — 183 deletes — maioria Prefetch" }], ["Export USN", "Contar deletes", "Timeline", "Relatório"]),
  L("det-recycle-bin", "Detecção: Lixeira Esvaziada", "deteccoes", "Lixeira limpa no horário do ban = esconder evidência.", [{ heading: "Como ver", body: "$Recycle.Bin ou journal mostra purge. Perguntar se esvaziou recentemente.", example: "User esvaziou lixeira 14:27 — journal confirma" }], ["Journal Recycle", "Perguntar user", "Cruzar timeline", "Anotar"]),
  L("det-downloads-desktop", "Detecção: Loader Downloads/Desktop", "deteccoes", "Cheater baixa e deixa loader visível.", [{ heading: "Locais", body: "Downloads\\setup.exe, Desktop\\update.exe — nomes genéricos.", example: "Desktop\\Client.exe — 1.2MB — criado hoje" }], ["Downloads", "Desktop", "DIE", "Prefetch"]),
  L("det-scheduled-task", "Detecção: Tarefa Agendada", "deteccoes", "Cheat persiste via Task Scheduler.", [{ heading: "Como", body: "taskschd.msc — tarefas apontando .exe em Temp ou script PowerShell.", example: "Task 'WindowsUpdate' → C:\\Temp\\loader.exe" }], ["Task Scheduler", "Ação da task", "Autor", "Print"]),
  L("det-run-registry", "Detecção: Run/RunOnce", "deteccoes", "Persistência em registry Run keys.", [{ heading: "Keys", body: "HKCU/HKLM\\...\\Run e RunOnce — valores apontando loader.", example: "Run: svchost → C:\\Users\\X\\AppData\\Local\\tmp\\svc.exe" }], ["regedit Run keys", "Valor suspeito", "Arquivo existe?", "SHA"]),
  L("det-dll-sem-assinatura", "Detecção: DLL Sem Assinatura", "deteccoes", "DLL em Temp sem Authenticode = inject material.", [{ heading: "Validar", body: "Propriedades → Assinaturas. Temp + unsigned + emulador com DLL carregada.", example: "inject.dll — unsigned — 892KB — System Informer confirma no HD-Player" }], ["Achar DLL", "Assinatura", "SI Modules", "SHA"]),
  L("det-hosts-modificado", "Detecção: Hosts Modificado", "deteccoes", "hosts file redirecionando auth ou blocking AV update.", [{ heading: "Arquivo", body: "C:\\Windows\\System32\\drivers\\etc\\hosts — entradas não padrão.", example: "127.0.0.1 update.microsoft.com — bloqueio update" }], ["Abrir hosts", "Entradas estranhas", "Data modificação", "Print"]),
  L("det-amcache", "Detecção: Amcache/Shimcache", "deteccoes", "Amcache registra execução de programas — backup quando prefetch sumiu.", [{ heading: "Uso", body: "Ferramentas parse Amcache. Mostra path, SHA, compile time.", example: "Amcache: loader.exe executado 14:30 — prefetch deletado" }], ["Parse Amcache", "Cruzar BAM", "SHA", "Timeline"]),
  L("det-browser-download", "Detecção: Download pelo Browser", "deteccoes", "Histórico do browser mostra de onde baixou cheat.", [{ heading: "Onde", body: "Chrome: History, Edge: Downloads. URL de site de cheat ou Discord CDN.", example: "Download: cheat-loader.zip de discord CDN às 14:00" }], ["Histórico browser", "Downloads folder", "URL", "Cruzar prefetch"]),
  L("det-srum", "Detecção: SRUM (Network)", "deteccoes", "System Resource Usage Monitor — tráfego por app com timestamp.", [{ heading: "Forense", body: "SRUM em registry — apps que consumiram rede com horário preciso.", example: "SRUM: unknown.exe 45MB 14:25-14:40" }], ["Parse SRUM", "App desconhecido", "Horário", "Cruzar scan"]),
  L("det-veredito-basico", "Detecção: Montar Veredito", "deteccoes", "Como fechar CLEAN, SUSPEITO ou BAN sem passar vergonha.", [{ heading: "Regras", body: "CLEAN = zero evidência concreta. SUSPEITO = indícios/anti-forense. BAN = prova (inject, auth+exec, delete mass).", example: "1 evidência forte OU 3+ médias = BAN\nSó prefetch vazio = SUSPEITO mínimo" }], ["Listar evidências", "Classificar força", "Veredito claro", "Prints datados"]),
];
