import type { Lesson } from "./types";

const L = (
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ id, title, categoryId, tier: "tier3", intro, sections, checklist });

export const tier3Lessons: Lesson[] = [
  L("dma-detectar", "DMA — Como Detectar", "privado", "Direct Memory Access via hardware (FPGA) — cheat que scanner de disco não pega.", [{ heading: "O que é", body: "Placa PCIe (FPGA) lê RAM do PC sem deixar rastro em processo. Muito usado em competitive.", example: "Scan disco: CLEAN\nTelagem manual: segunda PC lendo RAM\n→ DMA não aparece em Prefetch/Sysmon do alvo." }, { heading: "Sinais indiretos", body: "Cabo HDMI falso (fuser), segunda máquina na rede, placa PCIe desconhecida, comportamento inhuman sem processo." }, { heading: "171 ScreenS", body: "Área DMA/USB no painel enterprise. Correlacionar com hardware list." }], ["Área DMA scan", "Hardware PCIe", "Comportamento gameplay", "Regra servidor"]),
  L("dma-usb-hardware", "DMA & USB Programável", "privado", "Arduino, Teensy, Makcu — colorbot e input hardware.", [{ heading: "USB history", body: "Dispositivos programáveis conectados. VID/PID de Arduino, serial suspeito.", example: "USB: Arduino Leonardo — conectado durante ranked\n→ Input automation hardware" }, { heading: "Makcu/DMA kits", body: "Nomes comerciais mudam — foco em PCIe anômalo + USB serial + aim perfeito sem processo." }], ["USB history", "PCIe devices", "Scan USB area", "Print hardware"]),
  L("uefi-profundo", "UEFI Profundo — Além do Básico", "privado", "Análise firmware quando Tier II não basta.", [{ heading: "Boot chain", body: "Bootmgfw.efi modificado, hooks em boot services, variáveis NVRAM estranhas.", example: "ESP: bootmgfw.efi SHA diferente do stock\n→ Bootkit suspeito — escalar especialista" }, { heading: "Quando escalar", body: "Secure Boot off + ESP alterada + scan UEFI critical = não telar sozinho se não domina." }], ["Hash bootmgfw", "NVRAM dump", "Scan critical", "Escalar"]),
  L("uefi-esp-analise", "Análise da Partição ESP", "privado", "Listar e hash cada .efi na EFI System Partition.", [{ heading: "Como", body: "mountvol S: /S, dir S:\\EFI\\ — comparar com imagem clean do mesmo Windows.", example: "Arquivo extra: \\EFI\\Boot\\custom.efi\nCriado: 2 dias atrás" }], ["Mount ESP", "Listar .efi", "SHA cada arquivo", "Comparar stock"]),
  L("remote-bypass-deep", "Remote Bypass — Logs 3, Localhost, IP Local", "privado", "Remote disfarçado de tráfego local — tunnel, reverse, port forward.", [{ heading: "Event 3 localhost", body: "127.0.0.1:porta — processo local escutando para remote relay.", example: "Event 3:\nImage: anydesk.exe\nDestination: 127.0.0.1:5959\n→ Relay local ativo" }, { heading: "IP local LAN", body: "192.168.x.x entre dois PCs na mesma rede — segunda máquina controlando." }, { heading: "Logs + conexão", body: "Correlacionar Sysmon 3 + área REMOTE + netstat -ano." }], ["Event 3 filtro", "127.0.0.1", "LAN IPs", "netstat"]),
  L("remote-portas", "Portas Suspeitas em Telagem", "privado", "1337, 5555, 5938, 7070, portas custom de cheat/remote.", [{ heading: "netstat", body: "netstat -ano | findstr LISTENING — processo escutando porta não padrão.", example: "TCP 0.0.0.0:1337 — PID cheat_svc\n→ Backdoor local" }], ["netstat -ano", "PID → processo", "Sysmon Event 3", "Regra servidor"]),
  L("cheat-generico-privado", "Cheat Genérico — Caça Privada", "privado", "Métodos que Samuca usa em pins reais — não público.", [{ heading: "Abordagem", body: "Não confiar só no scan. Combo comportamento + memória + timeline + re-scan com strings custom enterprise.", example: "Pin #8842: scan clean\nDump: XOR string decode\nVeredito: BAN privado" }, { heading: "Strings custom", body: "Enterprise patterns no 171 ScreenS — atualizar conforme meta." }], ["Scan + dump", "Strings custom", "Timeline", "Review grupo"]),
  L("process-hollowing", "Process Hollowing — Detecção Completa", "privado", "Processo hollow: path legítimo, conteúdo de memória de outro binário.", [{ heading: "Técnica", body: "Create suspended → unmap → write malicious → resume. Parece svchost/notepad legítimo.", example: "svchost.exe sem -k servicegroup\nSI: memory não bate com disco\nEvent 8 start address anômalo" }, { heading: "Confirmar", body: "Compare Image on disk (DIE/SHA) vs memory modules. Mismatch = hollow." }], ["PPID tree", "Memory vs disk", "Event 8", "Veredito BAN"]),
  L("fileless-cmd", "Fileless — CMD Chains", "privado", "Cheat executado só por cmd.exe sem .exe persistente.", [{ heading: "Padrão", body: "cmd /c certutil -decode, bitsadmin, echo pipe para .bat em memória.", example: "Prefetch: CMD.EXE\nJournal: sem .exe novo\n4104: certutil -urlcache" }], ["CMD prefetch", "4104", "Certutil logs", "Memória"]),
  L("fileless-powershell", "Fileless — PowerShell", "privado", "IEX, DownloadString, -enc base64 — padrões fileless modernos.", [{ heading: "4104", body: "Script block mostra payload completo. Decode base64 offline.", example: "powershell -enc JABzAD0ATgBlAHcALQBPAGoAZQBjAHQ...\nDecode: download inject to memory" }, { heading: "AMSI bypass", body: "Strings ofuscadas, reflection — scan pode achar mesmo com bypass AMSI." }], ["4104 habilitado", "Decode -enc", "Parent process", "Sysmon 1"]),
  L("fileless-python", "Fileless — Python (py/pythonw)", "privado", "Cheat em script Python — pythonw sem janela.", [{ heading: "Sinais", body: "pythonw.exe no prefetch, pip install suspeito, .py em Temp, conexão Event 3.", example: "pythonw.exe prefetch 14:30\nTemp: aim.py\nEvent 3: auth IP" }], ["pythonw prefetch", "Scripts .py", "pip cache", "Event 3"]),
  L("metodos-privados", "Métodos Privados — Grupo Fechado", "privado", "Conteúdo exclusivo Tier III — atualiza conforme bypass evolui.", [{ heading: "Acesso", body: "Grupo Discord Private + calls de review. Casos reais anonimizados.", example: "Novo bypass semana X → módulo adicionado só Tier III" }], ["Entrar grupo", "Calls review", "Aplicar Tier I+II", "Feedback Samuca"]),
  L("labs-privado", "Labs & Review ao Vivo", "privado", "Telagem real com mentoria — aprendizado acelerado.", [{ heading: "Formato", body: "Aluno monta veredito → Samuca corrige ao vivo. Gravações exclusivas.", example: "Lab #12: pin DMA suspeito\nAluno: CLEAN\nCorreção: pedir hardware check" }], ["Preparar pin", "Defender veredito", "Anotar correções", "Revisar gravação"]),
  L("scanner-privado-internals", "171 ScreenS — Internals Private", "privado", "Extrair máximo do scanner: REMOTE, DMA, USB, enterprise strings.", [{ heading: "Áreas", body: "Cada área do result explicada com critério de ban do servidor.", example: "REMOTE + active session = BAN automático servidor X" }], ["Ler todas áreas", "Strings enterprise", "Rescan quando?", "Integrar curso"]),
  L("edge-cases-privado", "Edge Cases — Só Private", "privado", "Casos limite: VM, dual boot legítimo, dev tools, streamer setup.", [{ heading: "VM", body: "Hyper-V, VMware — diferenciar de emulador cheat. Nested virtualization.", example: "User dev legítimo: Hyper-V ON\nNão banir só por VM — contexto" }], ["Contexto user", "Regra servidor", "Evidência extra", "Documentar"]),
];
