import type { Lesson } from "./types";

const L = (
  order: number,
  id: string,
  title: string,
  categoryId: string,
  intro: string,
  sections: Lesson["sections"],
  checklist: string[]
): Lesson => ({ order, id, title, categoryId, tier: "tier2", intro, sections, checklist });

export const tier2Extra: Lesson[] = [
  L(36, "sysmon-event-7", "Sysmon Event 7 — Image Loaded", "sysmon",
    "DLL carregada em processo — inject deixa rastro aqui.",
    [{ heading: "Campos", body: "ImageLoaded path, Image (processo), Signed status.", example: "HD-Player.exe loads C:\\Temp\\hook.dll — Unsigned" }],
    ["Filtrar Event 7", "Unsigned em emulador", "Path Temp", "Print"]),
  L(37, "sysmon-event-15", "Sysmon Event 15 — FileCreateStreamHash", "sysmon",
    "ADS (Alternate Data Streams) — cheat escondido em :zone ou stream.",
    [{ heading: "ADS", body: "arquivo.txt:hidden.exe — NTFS alternate stream.", example: "Event 15: notepad.exe:malware.bin criado" }],
    ["Event 15", "Streams suspeitos", "dir /r", "Delete evidence"]),
  L(38, "sysmon-event-17", "Sysmon Event 17 — Pipe Created", "sysmon",
    "Named pipes — comunicação entre loader e cheat.",
    [{ heading: "Pipe", body: "\\\\.\\pipe\\nome_aleatorio — comum em cheat interno.", example: "Pipe: \\\\.\\pipe\\msagent_28f2" }],
    ["Event 17", "Pipe name", "Process creator", "Correlacionar"]),
  L(39, "volatility-intro", "Volatility — Intro Memória", "avancado",
    "Análise de RAM dump com framework Volatility — Tier II intro.",
    [{ heading: "Quando", body: "Dump .raw/.mem do PC — processos, DLLs, strings em RAM.", example: "vol -f dump.raw windows.pslist\n→ Processo oculto aparece" }],
    ["Obter dump RAM", "pslist", "dlllist", "Strings"]),
  L(40, "strings-advanced", "Strings — Caça Avançada", "avancado",
    "Extrair strings de .exe, .dll, dump — ASCII e Unicode.",
    [{ heading: "Ferramentas", body: "strings.exe, BinText, HxD. Buscar auth, aimbot, URLs.", example: "loader.exe strings:\nlicenseauth\ninject failed\n0x5 access denied" }],
    ["strings no binário", "Unicode também", "Auth URLs", "Documentar"]),
  L(41, "vt-interpretacao", "VirusTotal — Interpretar Resultado", "avancado",
    "VT 0/72 não é clean. VT 15/72 não é ban automático.",
    [{ heading: "Regra", body: "Cheat privado = 0 detecções. Packer conhecido = poucas detecções genéricas.", example: "VT 2/72 Heuristic — DIE VMProtect — Temp path\n→ Suspeito alto mesmo com VT baixo" }],
    ["SHA no VT", "Ler detecções", "Contexto path", "Não banir só VT"]),
  L(42, "ppid-spoofing", "PPID Spoofing", "avancado",
    "Processo com parent PID falso — parece filho de explorer.",
    [{ heading: "Detectar", body: "System Informer: parent não faz sentido. Sysmon Event 1 ParentImage vs real.", example: "loader.exe ParentImage: explorer.exe\nMas explorer não spawnou — SI mostra mismatch" }],
    ["SI process tree", "Event 1 Parent", "Compare timestamps", "Print"]),
  L(43, "lsass-access", "Acesso ao LSASS", "avancado",
    "Credential dump e alguns cheats acessam lsass — Event 10 target lsass.exe.",
    [{ heading: "Event 10", body: "Source suspeito com GrantedAccess alto em lsass.", example: "mimikatz pattern — Source unknown.exe → lsass" }],
    ["Event 10 lsass", "Source image", "Access mask", "Ban se confirmado"]),
  L(44, "wmi-persistence", "WMI — Persistência", "avancado",
    "Cheat via WMI subscription — fileless persistence.",
    [{ heading: "Detectar", body: "Get-WmiObject -Namespace root\\subscription. Consumer + Filter.", example: "WMI EventFilter trigger logon → Execute loader" }],
    ["WMI subscription", "Consumer command", "Filter query", "Remover evidência"]),
  L(45, "bcdedit-boot", "BCDEdit & Boot Config", "avancado",
    "Boot configuration alterada — test signing, nointegritychecks.",
    [{ heading: "Comando", body: "bcdedit /enum — testsigning Yes, nointegritychecks Yes = driver cheat.", example: "testsigning Yes\nnointegritychecks Yes\n→ Kernel driver load facilitado" }],
    ["bcdedit /enum", "testsigning", "nointegritychecks", "Secure Boot"]),
  L(46, "event-6008-6006", "Events 6006/6008 — Shutdown", "avancado",
    "Shutdown inesperado — user reiniciou pra limpar RAM ou crash de driver.",
    [{ heading: "System log", body: "6006 clean shutdown, 6008 unexpected. Reinício antes do SS.", example: "6008 14:25 — Scan pedido 14:30\n→ Reiniciou antes da telagem" }],
    ["System log", "Horário shutdown", "Gap antes scan", "Perguntar motivo"]),
  L(47, "event-104-log-clear", "Event 104 — Log Cleared (System)", "avancado",
    "Além do 1102 Security — System log também pode ser limpo.",
    [{ heading: "ID 104", body: "Microsoft-Windows-Eventlog — log System/Application cleared.", example: "Event 104 System cleared 14:27" }],
    ["Application log", "System log", "104 e 1102", "Timeline"]),
  L(48, "minifilter-drivers", "Minifilter & Drivers de File System", "avancado",
    "Driver de cheat kernel — minifilter intercepta arquivo.",
    [{ heading: "SI", body: "System → Drivers — não assinados, nome random.", example: "x7filter.sys — unsigned — loaded 13:00" }],
    ["Driver list", "Assinatura", "Load time", "Scan kernel"]),
  L(49, "network-capture", "Captura de Rede — Wireshark Intro", "avancado",
    "Durante telagem ao vivo — auth traffic em tempo real.",
    [{ heading: "Uso", body: "Wireshark loopback + adapter. Filtro ip.addr / dns.qry.name.", example: "DNS query licenseauth durante SS\n→ Auth ativo ao vivo" }],
    ["Captura durante SS", "Filtro DNS", "Auth domain", "Correlacionar processo"]),
  L(50, "relatorio-tier2", "Relatório Avançado — Tier II", "analise",
    "Relatório nível staff — timeline + Sysmon + memória.",
    [{ heading: "Estrutura", body: "Executive summary → Timeline → Sysmon highlights → Artefatos disco → Veredito → Recomendações", example: "TIMELINE 14:25-14:35 com 8 eventos\nVEREDITO BAN — 4 evidências independentes" }],
    ["Timeline visual", "Sysmon IDs citados", "SHA anexos", "Recomendação rescan"]),
];
